import { StyleSheet } from 'react-native';

export const NATIVE_STATUS_BAR_HEIGHT = 23;
export const STATUS_POPOVER_GAP = 8;
export const STATUS_POPOVER_BOTTOM_INSET = NATIVE_STATUS_BAR_HEIGHT + STATUS_POPOVER_GAP;

export const shellStyles = StyleSheet.create({
  header: {
    minHeight: 40,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  unifiedHeaderRow: { height: 32, flexDirection: 'row', alignItems: 'center', gap: 5 },
  projectTabGroup: { flexDirection: 'row', alignItems: 'center', gap: 4, flexShrink: 0 },
  globalButtonGroup: { flexDirection: 'row', alignItems: 'center', gap: 4, flexShrink: 0 },
  pluginPackingArea: { flex: 1, minWidth: 30, height: 32, position: 'relative', overflow: 'hidden', justifyContent: 'center' },
  pluginButtonGroup: { flexDirection: 'row', alignItems: 'center', gap: 5, minWidth: 0 },
  pluginMeasureLayer: { position: 'absolute', left: 0, top: 1, flexDirection: 'row', alignItems: 'center', gap: 5, opacity: 0 },
  headerDivider: { width: StyleSheet.hairlineWidth, height: 20, marginHorizontal: 1 },
  projectTab: { minWidth: 46, maxWidth: 114, height: 30, borderRadius: 8, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 3, paddingHorizontal: 9, flexShrink: 1 },
  projectTabText: { fontSize: 12, fontWeight: '700' },
  projectChevron: { width: 12, textAlign: 'center', fontSize: 12, lineHeight: 16, fontWeight: '700' },
  projectAdd: { width: 28, height: 30, borderRadius: 0, borderWidth: 0, backgroundColor: 'transparent', alignItems: 'center', justifyContent: 'center' },
  projectAddText: { fontSize: 19, lineHeight: 21, fontWeight: '500' },
  globalAction: { height: 30, minWidth: 38, maxWidth: 68, borderRadius: 8, borderWidth: 0, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8, flexShrink: 0 },
  globalActionText: { fontSize: 10.2, fontWeight: '600' },
  projectAction: { height: 30, minWidth: 0, maxWidth: 128, borderRadius: 8, borderWidth: StyleSheet.hairlineWidth, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 11, flexShrink: 0 },
  projectActionText: { fontSize: 10.2, fontWeight: '700' },
  moreAction: { width: 30, height: 30, borderRadius: 8, borderWidth: 0, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  moreActionText: { fontSize: 13, lineHeight: 16, letterSpacing: 1, fontWeight: '700' },
  moreGlyphCanvas: { width: 16, height: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  moreGlyphDot: { width: 3.2, height: 3.2, borderRadius: 2 },
  headerUtilityGroup: { flexDirection: 'row', alignItems: 'center', gap: 3, flexShrink: 0 },
  headerHistoryButton: { width: 30, height: 30, borderRadius: 8, borderWidth: StyleSheet.hairlineWidth, alignItems: 'center', justifyContent: 'center' },
  historyGlyphCanvas: { width: 15, height: 14, position: 'relative' },
  historyGlyphShaft: { position: 'absolute', left: 3.5, top: 6.3, width: 9, height: 1.2, borderRadius: .6 },
  historyGlyphTurn: { position: 'absolute', right: 2.5, top: 6.3, width: 1.2, height: 4.2, borderRadius: .6 },
  historyGlyphHeadA: { position: 'absolute', left: 2.2, top: 4.0, width: 5, height: 1.2, borderRadius: .6, transform: [{ rotate: '-36deg' }] },
  historyGlyphHeadB: { position: 'absolute', left: 2.2, top: 7.9, width: 5, height: 1.2, borderRadius: .6, transform: [{ rotate: '36deg' }] },
  headerParameterButton: { height: 30, minWidth: 42, maxWidth: 92, borderRadius: 8, borderWidth: StyleSheet.hairlineWidth, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 9 },
  headerParameterText: { fontSize: 10.2, fontWeight: '700' },
  nativeStatusBar: { height: NATIVE_STATUS_BAR_HEIGHT, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, gap: 11, position: 'relative', overflow: 'hidden' },
  nativeStatusMessageScroller: { flex: 1, minWidth: 92 },
  nativeStatusMessage: { fontSize: 10, lineHeight: 14, fontWeight: '400', paddingRight: 14 },
  nativeStatusItems: { flexDirection: 'row', flexShrink: 0, alignItems: 'center', justifyContent: 'flex-end', gap: 14, paddingLeft: 8 },
  nativeStatusItem: { height: 20, flexDirection: 'row', alignItems: 'center', gap: 4 },
  nativeStatusIcon: { width: 12, textAlign: 'center', fontSize: 8.5, lineHeight: 12, fontWeight: '400' },
  nativeStatusLabel: { fontSize: 9.3, lineHeight: 13, fontWeight: '400' },
  nativeStatusOverflow: { width: 24, height: 20, alignItems: 'center', justifyContent: 'center' },
  nativeStatusOverflowText: { fontSize: 10, lineHeight: 12, letterSpacing: .8, fontWeight: '700' },
  statusHistoryGlyphCanvas: { width: 12, height: 12, position: 'relative', alignSelf: 'center' },
  statusHistoryGlyphRing: { position: 'absolute', left: 1.7, top: 1.7, width: 8.6, height: 8.6, borderWidth: .8, borderRadius: 5 },
  statusHistoryGlyphHandH: { position: 'absolute', left: 5.7, top: 5.6, width: 3.0, height: .8, borderRadius: .4 },
  statusHistoryGlyphHandV: { position: 'absolute', left: 5.7, top: 3.5, width: .8, height: 3.0, borderRadius: .4 },
  statusHistoryGlyphTail: { position: 'absolute', left: .6, top: 2.0, width: 3.2, height: .8, borderRadius: .4, transform: [{ rotate: '-35deg' }] },
  statusGlyphCanvas: { width: 12, height: 12, position: 'relative', alignSelf: 'center' },
  statusGlyphGridA: { position:'absolute', left:1.2, top:1.2, width:4, height:4, borderWidth:.8, borderRadius:.8 },
  statusGlyphGridB: { position:'absolute', right:1.2, top:1.2, width:4, height:4, borderWidth:.8, borderRadius:.8 },
  statusGlyphGridC: { position:'absolute', left:1.2, bottom:1.2, width:4, height:4, borderWidth:.8, borderRadius:.8 },
  statusGlyphGridD: { position:'absolute', right:1.2, bottom:1.2, width:4, height:4, borderWidth:.8, borderRadius:.8 },
  statusGlyphMemory: { position:'absolute', left:1, top:2.2, width:10, height:7.6, borderWidth:.8, borderRadius:1.4 },
  statusGlyphMemoryLine: { position:'absolute', left:3, top:5.6, width:6, height:.8, borderRadius:.4 },
  statusGlyphTheme: { position:'absolute', left:1.5, top:1.5, width:9, height:9, borderWidth:.8, borderRadius:5 },
  statusGlyphThemeHalf: { position:'absolute', left:2.3, top:2.3, width:4.1, height:7.4, borderTopLeftRadius:4, borderBottomLeftRadius:4 },
  statusGlyphTerminal: { position:'absolute', left:1, top:2, width:10, height:8, borderWidth:.8, borderRadius:1.5 },
  statusGlyphTerminalLine: { position:'absolute', left:4.7, bottom:3.6, width:4.2, height:.8, borderRadius:.4 },
  statusGlyphAi: { position:'absolute', left:2.2, top:2.2, width:7.6, height:7.6, borderWidth:.8, borderRadius:1, transform:[{rotate:'45deg'}] },
  statusGlyphAiCore: { position:'absolute', left:5, top:5, width:2, height:2, borderRadius:1 },
  statusGlyphWeb: { position:'absolute', left:1.4, top:1.4, width:9.2, height:9.2, borderWidth:.8, borderRadius:5 },
  statusGlyphWebLine: { position:'absolute', left:2.4, top:5.6, width:7.2, height:.8, borderRadius:.4 },
  nativeStatusMeasureLayer: { position: 'absolute', right: 10, top: 1, height: 20, flexDirection: 'row', alignItems: 'center', gap: 14, opacity: 0 },
  pressed: { opacity: .82, transform: [{ scale: .985 }] },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  sheet: { maxHeight: '78%', borderTopLeftRadius: 22, borderTopRightRadius: 22, borderWidth: StyleSheet.hairlineWidth, paddingBottom: 10 },
  sheetHandle: { width: 38, height: 4, borderRadius: 2, alignSelf: 'center', marginTop: 8, marginBottom: 4 },
  sheetHeading: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17, paddingVertical: 10 },
  sheetTitle: { fontSize: 17, fontWeight: '700' },
  sheetSubtitle: { fontSize: 10, marginTop: 3, maxWidth: 290 },
  closeButton: { marginLeft: 'auto', width: 38, height: 38, alignItems: 'center', justifyContent: 'center' },
  closeButtonText: { fontSize: 25, fontWeight: '300' },
  sheetBody: { paddingHorizontal: 12, paddingBottom: 12, gap: 7 },
  sheetAction: { minHeight: 58, borderWidth: StyleSheet.hairlineWidth, borderRadius: 13, paddingHorizontal: 11, paddingVertical: 8, flexDirection: 'row', alignItems: 'center' },
  sheetActionGlyph: { width: 38, height: 38, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  sheetActionGlyphText: { fontSize: 17, fontWeight: '700' },
  sheetActionCopy: { flex: 1, minWidth: 0, marginLeft: 11 },
  sheetActionLabel: { fontSize: 13, fontWeight: '700' },
  sheetActionDetail: { fontSize: 9, marginTop: 3 },
  chevron: { fontSize: 24, fontWeight: '300', marginLeft: 8 },
  emptyText: { paddingVertical: 28, textAlign: 'center', fontSize: 12 },
  historySheetActions: { flexDirection: 'row', gap: 7, marginBottom: 4 },
  historySheetButton: { flex: 1, minHeight: 38, borderWidth: StyleSheet.hairlineWidth, borderRadius: 9, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center' },
  historySheetButtonText: { fontSize: 10.5, fontWeight: '600' },
  surfaceHeading: { fontSize: 10, fontWeight: '700', marginTop: 8, marginBottom: 1, paddingHorizontal: 4 },
  actionMenuGroup: { gap: 7 },
  projectDrawerModal: { flex: 1, alignItems: 'flex-start' },
  projectDrawer: { width: '82%', maxWidth: 350, height: '100%', borderRightWidth: StyleSheet.hairlineWidth, paddingTop: 18 },
  projectDrawerHead: { minHeight: 66, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17 },
  projectDrawerHeading: { fontSize: 17, fontWeight: '700' },
  projectDrawerSubheading: { fontSize: 9.5, marginTop: 4 },
  projectDrawerClose: { marginLeft: 'auto', width: 38, height: 38, alignItems: 'center', justifyContent: 'center' },
  projectQuickActions: { flexDirection: 'row', gap: 7, paddingHorizontal: 13, paddingBottom: 12 },
  projectQuickButton: { minHeight: 34, flex: 1, borderWidth: StyleSheet.hairlineWidth, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  projectQuickButtonText: { fontSize: 10.5, fontWeight: '600' },
  projectDrawerScroller: { flex: 1, minHeight: 0 },
  projectDrawerList: { paddingHorizontal: 12, paddingBottom: 12, gap: 8 },
  projectDrawerVersion: { flexShrink: 0, paddingHorizontal: 16, paddingTop: 8, paddingBottom: 12, fontSize: 9, textAlign: 'center', letterSpacing: .2 },
  projectDrawerRow: { height: 58, borderWidth: StyleSheet.hairlineWidth, borderRadius: 12, paddingLeft: 12, paddingRight: 7, flexDirection: 'row', alignItems: 'center' },
  projectDeleteIcon: { width: 34, height: 34, borderRadius: 9, alignItems: 'center', justifyContent: 'center', marginLeft: 4 },
  projectDeleteIconText: { fontSize: 22, lineHeight: 24, fontWeight: '300' },
  projectStateDot: { width: 14, height: 14, borderRadius: 7, borderWidth: 1.3, marginRight: 11 },
  projectDrawerCopy: { flex: 1, minWidth: 0 },
  projectDrawerTitle: { fontSize: 13, fontWeight: '600' },
  projectDrawerDetail: { fontSize: 9, marginTop: 3 },

});
