(() => {
  if(window.DKDSPluginDevTools)return;
  const VERSION='1.1.0';
  let overlay=null,body=null,activeTab='overview';
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
  const snapshot=async()=>{let history=null;try{history=await Promise.resolve(window.DKDSCapabilities?.invoke?.('core.project-history','state')||null);}catch{}return {plugin:window.DKDSPlugins?.diagnostics?.()||{},ui:window.DKDSUI?.diagnostics?.()||{},history,at:new Date().toISOString()};};
  function rowsOf(data){return Array.isArray(data)?data:[];}
  function badge(value,tone='neutral'){return `<span class="dkds-devtools-badge" data-tone="${esc(tone)}">${esc(value)}</span>`;}
  function metric(label,value,hint=''){return `<div class="dkds-devtools-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong>${hint?`<small>${esc(hint)}</small>`:''}</div>`;}
  function overview(data){const plugins=rowsOf(data.plugin?.plugins),ui=rowsOf(data.ui?.rows),active=plugins.filter(x=>x.active).length,failed=plugins.filter(x=>x.error||x.failure).length,layoutRisks=ui.reduce((n,row)=>n+rowsOf(row.workbenches).filter(x=>x?.riskCount>0||rowsOf(x?.risks).length).length,0);return `<div class="dkds-devtools-metrics">${metric('插件',plugins.length,`${active} active`)}${metric('UI Scope',ui.length)}${metric('布局风险',layoutRisks)}${metric('失败',failed)}</div><section class="dkds-devtools-section"><h3>当前工作区</h3><div class="dkds-devtools-kv"><span>SUPER</span><b>${esc(data.plugin?.workspace?.super?.pluginId||data.plugin?.workspace?.super?.id||'—')}</b><span>Plugin API</span><b>${esc(data.plugin?.apiVersion||'—')}</b><span>UI Runtime</span><b>${esc(data.ui?.version||'—')}</b><span>History</span><b>${data.history?.canUndo?'可撤销':'无撤销'} / ${data.history?.canRedo?'可重做':'无重做'}</b></div></section>`;}
  function surfaces(data){const scopes=rowsOf(data.ui?.rows);if(!scopes.length)return '<div class="dkds-devtools-empty">当前没有活动 UI Scope。</div>';return scopes.map(row=>`<section class="dkds-devtools-section"><h3>${esc(row.owner)}</h3><div class="dkds-devtools-chiprow">${badge(`${row.series?.count||0} series`,'info')}${badge(`${rowsOf(row.legendGroups).length} legend groups`)}${badge(`${row.tables||0} tables`)}${badge(`${row.plots?.count||rowsOf(row.plots?.rows).length||0} plot surfaces`)}</div></section>`).join('');}
  function layout(data){const groups=[];for(const scope of rowsOf(data.ui?.rows))for(const wb of rowsOf(scope.pluginWorkspaces))groups.push({owner:scope.owner,...wb});if(!groups.length)return '<div class="dkds-devtools-empty">尚无工作台布局诊断。</div>';return groups.map(row=>{const risks=rowsOf(row.risks);return `<section class="dkds-devtools-section"><h3>${esc(row.owner)} ${risks.length?badge(`${risks.length} risks`,'warning'):badge('contained','success')}</h3><div class="dkds-devtools-kv"><span>尺寸</span><b>${esc(`${row.width||0} × ${row.height||0}`)}</b><span>模式</span><b>${esc(row.mode||row.layoutMode||'auto')}</b></div>${risks.length?`<ul>${risks.map(x=>`<li>${esc(x.message||x.reason||x.type||JSON.stringify(x))}</li>`).join('')}</ul>`:''}</section>`;}).join('');}
  function series(data){const scopes=rowsOf(data.ui?.rows);const blocks=[];for(const scope of scopes){const items=rowsOf(scope.series?.rows||scope.series?.series);if(!items.length)continue;blocks.push(`<section class="dkds-devtools-section"><h3>${esc(scope.owner)}</h3><table class="dkds-devtools-table"><thead><tr><th>ID</th><th>Label</th><th>Color</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.label||x.name||'')}</td><td><span class="dkds-devtools-swatch" style="background:${esc(x.color||'transparent')}"></span>${esc(x.color||'—')}</td></tr>`).join('')}</tbody></table></section>`);}return blocks.join('')||'<div class="dkds-devtools-empty">尚无已注册 Series。</div>';}
  function history(data){const h=data.history||{};return `<div class="dkds-devtools-metrics">${metric('Undo',h.past?.length||0,h.undoLabel||'')}${metric('Redo',h.future?.length||0,h.redoLabel||'')}</div><section class="dkds-devtools-section"><h3>最近操作</h3>${rowsOf(h.past).slice(-12).reverse().map(x=>`<div class="dkds-devtools-history-row"><span>${esc(x.label)}</span><small>${x.createdAt?esc(new Date(x.createdAt).toLocaleTimeString()):''}</small></div>`).join('')||'<div class="dkds-devtools-empty">暂无历史。</div>'}</section>`;}
  function boundaries(data){const plugins=rowsOf(data.plugin?.plugins);return `<section class="dkds-devtools-section"><h3>运行时边界</h3><p>这里显示插件声明与运行状态，不再以原始 JSON 作为主界面。源码级 Plugin Boundary 仍由发布门禁执行。</p><table class="dkds-devtools-table"><thead><tr><th>Plugin</th><th>API</th><th>状态</th></tr></thead><tbody>${plugins.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.apiVersion||'—')}</td><td>${x.active?badge('active','success'):x.error?badge('error','danger'):badge('inactive')}</td></tr>`).join('')}</tbody></table></section>`;}
  function theme(){const Theme=window.DKDSTheme,coverage=Theme?.coverage?.()||null,renderer=Theme?.rendererCapabilities?.()||null,debug=window.DKDSThemeDebug,summary=coverage?.summary||{},profile=Theme?.profile?.()||'—',mode=Theme?.current?.()||'—',inspecting=debug?.isEnabled?.()===true;return `<div class="dkds-devtools-metrics">${metric('Theme',profile,mode)}${metric('Contract',Theme?.contractVersion||'—')}${metric('Material',renderer?.version||'—',renderer?.renderer?.backdropBlur?'renderer ready':'renderer unavailable')}${metric('Coverage',summary.ok?'PASS':'CHECK',`${summary.managed||0}/${summary.areas||0} areas`)}</div><section class="dkds-devtools-section"><h3>Theme Inspector ${inspecting?badge('running','success'):badge('stopped')}</h3><p>在真实业务 UI 上检查 Component Identity、Material Role、Appearance Slot、Resolved Token 与实际 computed style。交互检查开启后 DevTools 会收起；重新点击底部 DevTool 可返回此页停止检查。</p><div class="dkds-devtools-actions-row"><button type="button" data-act="theme-inspector">${inspecting?'停止交互检查':'开始交互检查'}</button><button type="button" data-act="theme-refresh">刷新 Theme 状态</button></div></section><section class="dkds-devtools-section"><h3>Coverage</h3><div class="dkds-devtools-kv"><span>Material</span><b>${esc(`${coverage?.coverage?.material?.managed||0}/${coverage?.coverage?.material?.present||0} managed`)}</b><span>Components</span><b>${esc(`${coverage?.coverage?.components?.managed||0}/${coverage?.coverage?.components?.present||0} managed`)}</b><span>Role mismatch</span><b>${esc(summary.roleMismatch||0)}</b><span>Authored unused</span><b>${esc(summary.authoredUnused||0)}</b><span>Low contrast</span><b>${esc(summary.lowContrastControls||0)}</b></div></section>`;}
  const renderers={overview,surfaces,layout,series,history,boundaries,theme};
  async function render(){if(!body)return;const data=await snapshot();if(!body)return;body.innerHTML=renderers[activeTab]?.(data)||overview(data);overlay.querySelectorAll('[data-devtab]').forEach(btn=>btn.classList.toggle('active',btn.dataset.devtab===activeTab));}
  function ensure(){if(overlay?.isConnected)return overlay;overlay=document.createElement('div');overlay.className='dkds-plugin-devtools hidden';overlay.innerHTML=`<div class="dkds-plugin-devtools-window" role="dialog" aria-label="Plugin DevTools"><header><div><strong>Plugin DevTools</strong><span>Core / SDK runtime inspector</span></div><div class="dkds-plugin-devtools-actions"><button data-act="chromium" type="button">Chromium</button><button data-act="refresh" type="button">刷新</button><button data-act="close" type="button">×</button></div></header><nav>${[['overview','概览'],['surfaces','Surface'],['layout','布局'],['series','Series'],['history','History'],['boundaries','Boundary'],['theme','Theme']].map(([id,label])=>`<button type="button" data-devtab="${id}">${label}</button>`).join('')}</nav><main></main></div>`;(document.body||document.documentElement).appendChild(overlay);body=overlay.querySelector('main');overlay.addEventListener('click',async e=>{const tab=e.target.closest('[data-devtab]');if(tab){activeTab=tab.dataset.devtab;void render();return;}const act=e.target.closest('[data-act]')?.dataset.act;if(act==='close')close();if(act==='refresh')void render();if(act==='chromium')try{await window.electronAPI?.toggleDevTools?.();}catch{}if(act==='theme-refresh')void render();if(act==='theme-inspector'){const debug=window.DKDSThemeDebug;if(!debug)return;if(debug.isEnabled?.()){debug.disable?.();void render();}else{debug.enable?.();close();}}});return overlay;}
  function open(tab='overview'){ensure();activeTab=renderers[tab]?tab:'overview';overlay.classList.remove('hidden');void render();return true;}
  function close(){overlay?.classList.add('hidden');return true;}
  function toggle(tab='overview'){ensure();if(overlay.classList.contains('hidden'))return open(tab);return close();}
  window.DKDSPluginDevTools=Object.freeze({VERSION,open,close,toggle,refresh:()=>render(),snapshot});
})();
