(() => {
  if(window.DKDSPluginDevTools)return;
  const VERSION='1.7.0';
  let overlay=null,body=null,activeTab='overview',keyHandler=null;
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
  const snapshot=async()=>{let history=null;try{history=await Promise.resolve(window.DKDSCapabilities?.invoke?.('core.project-history','state')||null);}catch{}return {plugin:window.DKDSPlugins?.diagnostics?.()||{},ui:window.DKDSUI?.diagnostics?.()||{},history,core:{components:window.DKDSComponents?.diagnostics?.()||null,frames:window.DKDSFrameScheduler?.snapshot?.()||null,mutations:window.DKDSDOMMutationHub?.snapshot?.()||null,performance:window.DKDSPerformance?.snapshot?.()||null,styleGate:window.DKDSStyleGate?.snapshot?.()||null},at:new Date().toISOString()};};
  function rowsOf(data){return Array.isArray(data)?data:[];}
  function badge(value,tone='neutral'){return `<span class="dkds-devtools-badge" data-tone="${esc(tone)}">${esc(value)}</span>`;}
  function metric(label,value,hint=''){return `<div class="dkds-devtools-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong>${hint?`<small>${esc(hint)}</small>`:''}</div>`;}
  function applyRuntimeStyles(root){const gate=window.DKDSStyleGate;if(!gate)return;for(const swatch of root?.querySelectorAll?.('[data-devtools-swatch-color]')||[])gate.set(swatch,'background',swatch.dataset.devtoolsSwatchColor||'transparent',{owner:'core.plugin-devtools',component:'devtools-swatch',kind:'runtime-inline',source:'src/core/plugins/devtools.js'});}
  function overview(data){const plugins=rowsOf(data.plugin?.plugins),ui=rowsOf(data.ui?.rows),active=plugins.filter(x=>x.active).length,failed=plugins.filter(x=>x.error||x.failure).length,layoutRisks=ui.reduce((n,row)=>n+rowsOf(row.workbenches).filter(x=>x?.riskCount>0||rowsOf(x?.risks).length).length,0),components=data.core?.components||{},frames=data.core?.frames||{},mutations=data.core?.mutations||{},perf=data.core?.performance?.totals||{},styleGate=data.core?.styleGate||{},liveResources=rowsOf(components.resources).reduce((sum,row)=>sum+(Number(row.count)||0),0);return `<div class="dkds-devtools-metrics">${metric('插件',plugins.length,`${active} active`)}${metric('UI Scope',ui.length)}${metric('布局风险',layoutRisks)}${metric('失败',failed)}</div><section class="dkds-devtools-section"><h3>Runtime Pressure</h3><div class="dkds-devtools-metrics">${metric('DOM scopes',components.activeScopes||0,`${liveResources} tracked resources`)}${metric('Frame queue',frames.pending||0,`peak ${frames.maxPending||0} · coalesced ${frames.coalesced||0}`)}${metric('Mutation hub',mutations.subscribers||0,`max batch ${mutations.maxBatchRecords||0}`)}${metric('Core cache',perf.entries||0,`evictions ${perf.evictions||0} · trims ${perf.trims||0}`)}${metric('Style Gate',styleGate.validation?.ok===false?'CONFLICT':'PASS',`${styleGate.activeClaims||0} claims · ${styleGate.inlineClaims||0} inline · ${styleGate.paintClaims||0} paint · ${styleGate.presentationClaims||0} presentation · ${styleGate.conflictCount||0} conflicts · ${styleGate.unauthorizedObserved||0} bypass`)}</div></section><section class="dkds-devtools-section"><h3>当前工作区</h3><div class="dkds-devtools-kv"><span>SUPER</span><b>${esc(data.plugin?.workspace?.super?.pluginId||data.plugin?.workspace?.super?.id||'—')}</b><span>Plugin API</span><b>${esc(data.plugin?.apiVersion||'—')}</b><span>UI Runtime</span><b>${esc(data.ui?.version||'—')}</b><span>History</span><b>${data.history?.canUndo?'可撤销':'无撤销'} / ${data.history?.canRedo?'可重做':'无重做'}</b></div></section>`;}
  function surfaces(data){const scopes=rowsOf(data.ui?.rows);if(!scopes.length)return '<div class="dkds-devtools-empty">当前没有活动 UI Scope。</div>';return scopes.map(row=>`<section class="dkds-devtools-section"><h3>${esc(row.owner)}</h3><div class="dkds-devtools-chiprow">${badge(`${row.series?.count||0} series`,'info')}${badge(`${rowsOf(row.legendGroups).length} legend groups`)}${badge(`${row.tables||0} tables`)}${badge(`${row.plots?.count||rowsOf(row.plots?.rows).length||0} plot surfaces`)}</div></section>`).join('');}
  function layout(data){const groups=[];for(const scope of rowsOf(data.ui?.rows))for(const wb of rowsOf(scope.pluginWorkspaces))groups.push({owner:scope.owner,...wb});if(!groups.length)return '<div class="dkds-devtools-empty">尚无工作台布局诊断。</div>';return groups.map(row=>{const risks=rowsOf(row.risks);return `<section class="dkds-devtools-section"><h3>${esc(row.owner)} ${risks.length?badge(`${risks.length} risks`,'warning'):badge('contained','success')}</h3><div class="dkds-devtools-kv"><span>尺寸</span><b>${esc(`${row.width||0} × ${row.height||0}`)}</b><span>模式</span><b>${esc(row.mode||row.layoutMode||'auto')}</b></div>${risks.length?`<ul>${risks.map(x=>`<li>${esc(x.message||x.reason||x.type||JSON.stringify(x))}</li>`).join('')}</ul>`:''}</section>`;}).join('');}
  function series(data){const scopes=rowsOf(data.ui?.rows);const blocks=[];for(const scope of scopes){const items=rowsOf(scope.series?.rows||scope.series?.series);if(!items.length)continue;blocks.push(`<section class="dkds-devtools-section"><h3>${esc(scope.owner)}</h3><table class="dkds-devtools-table"><thead><tr><th>ID</th><th>Label</th><th>Color</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.label||x.name||'')}</td><td><span class="dkds-devtools-swatch" data-devtools-swatch-color="${esc(x.color||'transparent')}"></span>${esc(x.color||'—')}</td></tr>`).join('')}</tbody></table></section>`);}return blocks.join('')||'<div class="dkds-devtools-empty">尚无已注册 Series。</div>';}
  function history(data){const h=data.history||{};return `<div class="dkds-devtools-metrics">${metric('Undo',h.past?.length||0,h.undoLabel||'')}${metric('Redo',h.future?.length||0,h.redoLabel||'')}</div><section class="dkds-devtools-section"><h3>最近操作</h3>${rowsOf(h.past).slice(-12).reverse().map(x=>`<div class="dkds-devtools-history-row"><span>${esc(x.label)}</span><small>${x.createdAt?esc(new Date(x.createdAt).toLocaleTimeString()):''}</small></div>`).join('')||'<div class="dkds-devtools-empty">暂无历史。</div>'}</section>`;}
  function boundaries(data){const plugins=rowsOf(data.plugin?.plugins);return `<section class="dkds-devtools-section"><h3>运行时边界</h3><p>这里显示插件声明与运行状态，不再以原始 JSON 作为主界面。源码级 Plugin Boundary 仍由发布门禁执行。</p><table class="dkds-devtools-table"><thead><tr><th>Plugin</th><th>API</th><th>状态</th></tr></thead><tbody>${plugins.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.apiVersion||'—')}</td><td>${x.active?badge('active','success'):x.error?badge('error','danger'):badge('inactive')}</td></tr>`).join('')}</tbody></table></section>`;}
  const shortSource=value=>String(value||'').split('/').slice(-3).join('/');
  function ownerSourceChain(row={},ownerKey='ownerSources'){
    const pairs=rowsOf(row?.[ownerKey]);
    if(pairs.length)return pairs.map(pair=>`${pair?.owner||'unclaimed'} → ${rowsOf(pair?.sources).length?rowsOf(pair.sources).map(shortSource).join(', '):'source unavailable'}`).join(' | ');
    const owners=rowsOf(ownerKey==='declaredOwnerSources'?row.declaredOwners:row.owners),sources=rowsOf(ownerKey==='declaredOwnerSources'?row.declaredSources:row.sources);
    if(!owners.length)return `unclaimed → ${sources.length?sources.map(shortSource).join(', '):'caller unavailable'}`;
    return owners.map(owner=>`${owner} → ${sources.length?sources.map(shortSource).join(', '):'source unavailable'}`).join(' | ');
  }
  const contextState=(row={})=>({context:String(row.actualContext||row.context||'*'),state:String(row.state||'runtime')});
  function diagnosticSources(row={},ownerKey='ownerSources'){
    const pairs=rowsOf(row?.[ownerKey]);
    const sources=pairs.length?pairs.flatMap(pair=>rowsOf(pair?.sources)):rowsOf(ownerKey==='declaredOwnerSources'?row.declaredSources:row.sources);
    return [...new Set(sources.map(value=>String(value||'').trim()).filter(Boolean))];
  }
  function sourceCopyButton(row={},ownerKey='ownerSources'){const text=diagnosticSources(row,ownerKey).join('\n');return text?`<button type="button" data-act="style-source-copy" data-style-source="${esc(text)}" data-dkds-native-copy="clipboard" title="${esc(text)}">复制来源</button>`:'';}
  function gateDiagnostics(gate={}){
    const conflicts=rowsOf(gate.conflictEvents).slice(-4).reverse().map(row=>({type:'conflict',slot:`${row.component||'component'} · ${row.slot||''}`,path:ownerSourceChain(row),...contextState(row)}));
    const bypasses=rowsOf(gate.unauthorizedEvents).slice(-6).reverse().map(row=>({type:'bypass',slot:`${row.component||'component'} · ${row.slot||''}`,path:ownerSourceChain(row,'declaredOwnerSources'),...contextState(row)}));
    const rows=[...bypasses,...conflicts].slice(0,8);if(!rows.length)return '<div class="dkds-devtools-empty">当前运行时没有 Style Gate conflict / bypass 事件。</div>';
    return `<table class="dkds-devtools-table"><thead><tr><th>Type</th><th>Component / slot</th><th>Owner → source</th><th>Source</th><th>Context</th><th>State</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row.type)}</td><td>${esc(row.slot)}</td><td>${esc(row.path)}</td><td>${sourceCopyButton(row,row.type==='bypass'?'declaredOwnerSources':'ownerSources')}</td><td>${esc(row.context)}</td><td>${esc(row.state)}</td></tr>`).join('')}</tbody></table>`;
  }
  function selectedTraceDiagnostics(trace){
    const rows=rowsOf(trace?.diagnostics?.rows).slice(0,16);if(!trace)return '<div class="dkds-devtools-empty">Theme Inspector 尚未固定元素。</div>';if(!rows.length)return '<div class="dkds-devtools-empty">当前固定元素没有 managed Style Gate diagnostics。</div>';
    return `<table class="dkds-devtools-table"><thead><tr><th>Status</th><th>Slot</th><th>Owner → source</th><th>Source</th><th>Context</th><th>State</th></tr></thead><tbody>${rows.map(row=>{const cs=contextState(row);return `<tr><td>${esc(row.status||'—')}</td><td>${esc(`${row.type||'style'} · ${row.slot||''}`)}</td><td>${esc(ownerSourceChain(row))}</td><td>${sourceCopyButton(row)}</td><td>${esc(cs.context)}</td><td>${esc(cs.state)}</td></tr>`;}).join('')}</tbody></table>`;
  }
  function theme(){const Theme=window.DKDSTheme,coverage=Theme?.coverage?.()||null,renderer=Theme?.rendererCapabilities?.()||null,debug=window.DKDSThemeDebug,summary=coverage?.summary||{},profile=Theme?.profile?.()||'—',mode=Theme?.current?.()||'—',inspecting=debug?.isEnabled?.()===true,trace=debug?.currentTrace?.()||null,gate=window.DKDSStyleGate?.snapshot?.()||{},traceOwners=trace?[...Object.values(trace.groups||{}).map(group=>`${group.name}:${group.ownerModules?.join('+')||group.status}`),...Object.values(trace.runtimeGateGroups||{}).map(group=>`${group.label}:${group.rows?.length||0}`)].join(' · '):'';return `<div class="dkds-devtools-metrics">${metric('Theme',profile,mode)}${metric('Contract',Theme?.contractVersion||'—')}${metric('Material',renderer?.version||'—',renderer?.renderer?.backdropBlur?'renderer ready':'renderer unavailable')}${metric('Coverage',summary.ok?'PASS':'CHECK',`${summary.managed||0}/${summary.areas||0} areas`)}${metric('Style Trace',trace?.status||'—',traceOwners||'pin an element in Inspector')}${metric('Style Gate',gate.validation?.ok===false?'CONFLICT':'PASS',`${gate.activeClaims||0} claims · ${gate.inlineClaims||0} inline · ${gate.paintClaims||0} paint · ${gate.presentationClaims||0} presentation · ${gate.conflictCount||0} conflicts · ${gate.unauthorizedObserved||0} bypass`)}</div><section class="dkds-devtools-section"><h3>Theme Inspector ${inspecting?badge('running','success'):badge('stopped')}</h3><p>在真实业务 UI 上检查 Component Identity、Material Role、Appearance Slot、Resolved Token 与实际 computed style。固定元素后会把 Authored Geometry / Paint / Motion 与 Runtime inline / paint / presentation 分组显示，并解析配置 token 来源以及 Interaction / lifecycle owner。开始检查后 DevTools 会收起。重新打开 DevTool 时检查 HUD 与页面拦截会自动暂停，并直接进入 Theme 页；可在这里停止检查。若直接关闭 DevTool 且未停止检查，Inspector 会恢复。Inspector HUD 自身也可用 × 或 Esc 退出。</p><div class="dkds-devtools-actions-row"><button type="button" data-act="theme-inspector">${inspecting?'停止交互检查':'开始交互检查'}</button><button type="button" data-act="theme-refresh">刷新 Theme 状态</button></div></section><section class="dkds-devtools-section"><h3>Selected Style Trace</h3><p>固定元素后按 owner → source → context → state 显示唯一所有权链；generic expectation 会同时显示实际上下文。</p>${selectedTraceDiagnostics(trace)}</section><section class="dkds-devtools-section"><h3>Style Gate events</h3>${gateDiagnostics(gate)}</section><section class="dkds-devtools-section"><h3>Coverage</h3><div class="dkds-devtools-kv"><span>Material</span><b>${esc(`${coverage?.coverage?.material?.managed||0}/${coverage?.coverage?.material?.present||0} managed`)}</b><span>Components</span><b>${esc(`${coverage?.coverage?.components?.managed||0}/${coverage?.coverage?.components?.present||0} managed`)}</b><span>Role mismatch</span><b>${esc(summary.roleMismatch||0)}</b><span>Authored unused</span><b>${esc(summary.authoredUnused||0)}</b><span>Low contrast</span><b>${esc(summary.lowContrastControls||0)}</b></div></section>`;}
  const renderers={overview,surfaces,layout,series,history,boundaries,theme};
  async function render(){if(!body)return;if(activeTab==='theme')await window.DKDSOptionalRuntime?.ensureThemeTooling?.();const data=await snapshot();if(!body)return;body.innerHTML=renderers[activeTab]?.(data)||overview(data);applyRuntimeStyles(body);overlay.querySelectorAll('[data-devtab]').forEach(btn=>{const selected=btn.dataset.devtab===activeTab;btn.classList.toggle('selected',selected);btn.setAttribute('aria-selected',selected?'true':'false');btn.tabIndex=selected?0:-1;});}
  function ensure(){if(overlay?.isConnected)return overlay;overlay=document.createElement('div');overlay.className='dkds-plugin-devtools hidden';overlay.innerHTML=`<div class="dkds-plugin-devtools-window dkds-material-role-elevated" role="dialog" aria-label="Plugin DevTools"><header class="dkds-surface-header"><div><strong>Plugin DevTools</strong><span>Core / SDK runtime inspector</span></div><div class="dkds-plugin-devtools-actions"><button data-act="chromium" type="button">Chromium</button><button data-act="refresh" type="button">刷新</button><button data-act="close" class="dkds-panel-close-button" type="button" aria-label="关闭 Plugin DevTools" title="关闭 Plugin DevTools">×</button></div></header><nav role="tablist" aria-label="Plugin DevTools 页面">${[['overview','概览'],['surfaces','Surface'],['layout','布局'],['series','Series'],['history','History'],['boundaries','Boundary'],['theme','Theme']].map(([id,label])=>`<button type="button" role="tab" aria-selected="${id===activeTab?'true':'false'}" data-devtab="${id}">${label}</button>`).join('')}</nav><main></main></div>`;(document.body||document.documentElement).appendChild(overlay);globalThis.DKDSMaterialSurface?.apply?.(overlay.querySelector('.dkds-plugin-devtools-window'),'elevated');body=overlay.querySelector('main');overlay.addEventListener('click',async e=>{if(e.target===overlay){close();return;}const tab=e.target.closest('[data-devtab]');if(tab){activeTab=tab.dataset.devtab;void render();return;}const act=e.target.closest('[data-act]')?.dataset.act;if(act==='close')close();if(act==='refresh')void render();if(act==='chromium')try{await window.electronAPI?.toggleDevTools?.();}catch{}if(act==='style-source-copy'){const source=e.target.closest('[data-style-source]')?.dataset.styleSource;if(source)try{await (window.DKDSIO?.clipboard?.writeText?.(source)||navigator.clipboard?.writeText?.(source));}catch{}return;}if(act==='theme-refresh')void render();if(act==='theme-inspector'){await window.DKDSOptionalRuntime?.ensureThemeTooling?.();const debug=window.DKDSThemeDebug;if(!debug)return;if(debug.isEnabled?.()){debug.disable?.();void render();}else{debug.enable?.();close();}}});return overlay;}
  function open(tab='overview'){
    ensure();
    const debug=window.DKDSThemeDebug;
    if(debug?.isEnabled?.()&&tab==='overview')tab='theme';
    debug?.pause?.('devtools');
    activeTab=renderers[tab]?tab:'overview';
    overlay.classList.remove('hidden');
    if(!keyHandler){keyHandler=event=>{if(event.key==='Escape'&&!overlay?.classList.contains('hidden')){event.preventDefault();event.stopPropagation();close();}};window.addEventListener('keydown',keyHandler,true);}
    void render();
    return true;
  }
  function close(){
    overlay?.classList.add('hidden');
    if(keyHandler){window.removeEventListener('keydown',keyHandler,true);keyHandler=null;}
    window.DKDSThemeDebug?.resume?.('devtools');
    return true;
  }
  function toggle(tab='overview'){ensure();if(overlay.classList.contains('hidden'))return open(tab);return close();}
  window.DKDSPluginDevTools=Object.freeze({VERSION,open,close,toggle,refresh:()=>render(),snapshot});
})();
