(() => {
  'use strict';
  const VERSION='4.1.0';
  const StyleGate=globalThis.DKDSStyleGate;
  if(!StyleGate)throw new Error('DKDSStyleGate must initialize before Theme Gallery.');
  const STYLE_OWNER='core.theme-gallery';
  const STYLE_SOURCE='src/core/theme/test-gallery.js';
  const BASE={
    light:{canvas:'#eef4fb',surface:'#fbfcfe',surfaceSoft:'#f6f9fd',surfaceElevated:'#fff',surfaceSidebar:'#f7f9fc',controlBg:'#fbfcfe',controlHover:'#f0f5fc',controlBorder:'rgba(102,132,168,.22)',divider:'rgba(102,132,168,.085)',text:'#1c2a43',textSoft:'#60708c',muted:'#7f8ba8',accent:'#096bfa',accentSoft:'#eaf2ff'},
    dark:{canvas:'#151922',surface:'#1d232e',surfaceSoft:'#202733',surfaceElevated:'#222a36',surfaceSidebar:'#191f29',controlBg:'#232b37',controlHover:'#2a3442',controlBorder:'rgba(166,181,202,.16)',divider:'rgba(166,181,202,.024)',text:'#e4e9f2',textSoft:'#b5c0d0',muted:'#8995a8',accent:'#4d8dff',accentSoft:'#202d55'}
  };
  const kebab=value=>String(value||'').replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`),cssName=key=>`--dkui-${kebab(key)}`,roleVar=(role,key)=>`--dkui-role-${kebab(role)}-${kebab(key)}`,componentVar=(component,key)=>`--dkui-component-${kebab(component)}-${kebab(key)}`,variantVar=(component,variant,key)=>`--dkui-component-${kebab(component)}-variant-${kebab(variant)}-${kebab(key)}`;
  const materialMap={materialBlur:'blur',materialBlurStrong:'blur-strong',materialSaturation:'saturation',materialTintOpacity:'tint-opacity',specularHighlight:'specular-highlight',innerHighlight:'inner-highlight',glassEdge:'glass-edge',materialNoiseOpacity:'noise-opacity'};
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  function previewVars(profileId,mode){
    const preview=window.DKDSTheme?.preview?.(profileId,mode)||{tokens:{},appearance:{roles:{},components:{}},effects:{},material:{base:{},roles:{}},scientific:{seriesPalette:[]}},vars=[],tokens={...BASE[mode],...(preview.tokens||{})};
    for(const [key,value] of Object.entries(tokens))vars.push(`${cssName(key)}:${value}`);
    for(const [role,values] of Object.entries(preview.appearance?.roles||{}))for(const [key,value] of Object.entries(values||{}))vars.push(`${roleVar(role,key)}:${value}`);
    for(const [component,values] of Object.entries(preview.appearance?.components||{}))for(const [key,value] of Object.entries(values||{})){if(key==='variants'){for(const [variant,row] of Object.entries(value||{}))for(const [slot,variantValue] of Object.entries(row||{}))vars.push(`${variantVar(component,variant,slot)}:${variantValue}`);}else vars.push(`${componentVar(component,key)}:${value}`);}
    for(const [key,value] of Object.entries(preview.effects||{})){vars.push(`--dkui-effect-${kebab(key)}:${value}`);if(key==='gradientDirection')vars.push(`--dkui-effect-gradient-angle:${{horizontal:'90deg',vertical:'180deg','diagonal-down':'135deg','diagonal-up':'45deg'}[value]||'90deg'}`);}
    for(const [key,value] of Object.entries(preview.material?.base||{}))if(materialMap[key])vars.push(`--dkui-material-${materialMap[key]}:${value}`);
    for(const [role,values] of Object.entries(preview.material?.roles||{}))for(const [key,value] of Object.entries(values||{}))if(materialMap[key])vars.push(`--dkui-material-${role}-${materialMap[key]}:${value}`);
    const palette=preview.scientific?.seriesPalette||[];for(let i=0;i<8;i++)vars.push(`--dkds-gallery-series-${i}:${palette[i]||['#2563eb','#0f9f94','#7c3aed','#e5484d','#d97706','#0891b2','#be185d','#65a30d'][i]}`);
    return {style:vars.join(';'),preview};
  }
  const meta=component=>`<small class="dkds-theme-gallery-meta" data-gallery-meta data-component="${escapeHtml(component)}">${escapeHtml(component)}</small>`;
  const block=(title,body,component)=>`<article class="dkds-theme-gallery-demo"><div class="dkds-theme-gallery-demo-title">${escapeHtml(title)}</div>${body}${meta(component)}</article>`;
  function panel(profileId,mode){
    const {style}=previewVars(profileId,mode);
    const plot=`<div class="dkds-theme-gallery-plot"><div class="dkds-plot-view-head dkds-material-role-chrome"><strong class="dkds-plot-view-title">ScientificPlot</strong><div class="dkds-plot-view-actions"><button class="dkds-plot-view-action">□</button><button class="dkds-plot-view-action">↧</button></div></div><svg viewBox="0 0 300 110" aria-label="scientific palette preview"><path class="dkds-theme-gallery-series-0" d="M8 84 C45 68 65 20 112 52 S200 22 292 36"/><path class="dkds-theme-gallery-series-1" d="M8 72 C60 84 105 31 150 58 S235 32 292 48"/><path class="dkds-theme-gallery-axis" d="M8 94H292M8 8V94"/></svg><div class="dkds-theme-gallery-legend"><span><i data-gallery-swatch="0"></i>Series 1</span><span><i data-gallery-swatch="1"></i>Series 2</span></div></div>`;
    const table=`<div class="dkds-theme-gallery-table"><table><thead><tr><th>Vg</th><th>Vd</th><th>I</th></tr></thead><tbody><tr><td>0</td><td>.2</td><td>1.24µ</td></tr><tr><td>5</td><td>.4</td><td>2.51µ</td></tr></tbody></table></div>`;
    return `<section class="dkds-theme-gallery-mode" data-gallery-mode="${mode}" data-gallery-style="${escapeHtml(style)}"><header class="dkds-theme-gallery-chrome dkds-material-role-chrome"><strong>${mode==='light'?'亮色':'暗色'}</strong><span>Theme 3.9 canonical components</span></header><div class="dkds-theme-gallery-body"><aside class="dkds-theme-gallery-sidebar dkds-material-role-sidebar"><strong>Semantic roles</strong><span>Chrome</span><span>Sidebar</span><span>Surface</span><span>Elevated</span><span>Popover</span><span>Control</span><span>Floating</span></aside><main class="dkds-theme-gallery-main"><div class="dkds-theme-gallery-component-grid">
      ${block('Tab',`<div class="dkds-theme-gallery-tabs"><button class="activity-tab">Idle</button><button class="activity-tab active">Active</button><button class="activity-tab selected" aria-selected="true">Selected</button></div>`,'tab')}
      ${block('Toolbar Action',`<div class="dkds-theme-gallery-toolbar-actions"><button class="toolbar-btn">Default</button><button class="toolbar-btn active" aria-pressed="true">Active</button><button class="toolbar-btn primary">Primary</button><button class="toolbar-btn" data-dkds-action-tone="secondary">Secondary</button></div>`,'toolbarAction')}
      ${block('Toolbar Group',`<div class="toolbar-group"><button class="toolbar-btn">A</button><button class="toolbar-btn">B</button></div>`,'toolbarGroup')}
      ${block('Panel Header',`<div class="dkds-surface-header"><strong>Panel Header</strong><button class="dkds-icon-button">⋯</button></div>`,'panelHeader')}
      ${block('Inspector Header',`<div class="floating-header" data-dkds-inspector-header><strong>Inspector Header</strong><span>Vd</span></div>`,'inspectorHeader')}
      ${block('Field',`<div class="dkds-theme-gallery-fields"><input value="Field" readonly><select><option>Select</option></select><textarea readonly>Text</textarea></div>`,'field')}
      ${block('Menu Item',`<div class="dkds-theme-gallery-menu dkds-material-role-popover"><button class="plugin-menu-item" role="menuitem">Menu item</button><button class="plugin-menu-item selected" role="menuitem" aria-selected="true">Selected</button></div>`,'menuItem')}
      ${block('Chip',`<div class="dkds-theme-gallery-chips"><span class="dkds-chip">Chip</span><span class="dkds-chip selected" aria-selected="true">Selected</span><span class="dkds-chip" data-status="success">Success</span></div>`,'chip')}
      ${block('Floating Chrome',`<div class="dkds-theme-gallery-floating dkds-material-role-floating" data-dkds-floating-chrome><strong>Floating Chrome</strong><div><button class="dkds-icon-button">−</button><button class="dkds-icon-button">+</button></div></div>`,'floatingChrome')}
      ${block('Status Bar',`<div class="statusbar"><span>Ready</span><span class="dkds-summary-chip">Theme</span><span>12 MB</span></div>`,'statusBar')}
    </div><div class="dkds-theme-gallery-science-grid"><article class="dkds-theme-gallery-demo"><div class="dkds-theme-gallery-demo-title">ScientificPlot / neutral data surface</div>${plot}</article><article class="dkds-theme-gallery-demo"><div class="dkds-theme-gallery-demo-title">Table / neutral data surface</div>${table}</article></div><div class="dkds-theme-gallery-tooltip dkds-material-role-popover"><strong>Tooltip / Popover</strong><span>Vd = 0.42 V</span></div></main></div></section>`;
  }
  function applyGalleryRuntimeStyles(root){
    for(const section of root?.querySelectorAll?.('[data-gallery-style]')||[]){const text=String(section.dataset.galleryStyle||'');for(const declaration of text.split(';')){const idx=declaration.indexOf(':');if(idx<=0)continue;const property=declaration.slice(0,idx).trim(),value=declaration.slice(idx+1).trim();if(!property||!value)continue;if(property.startsWith('--'))StyleGate.setToken(section,property,value,{owner:STYLE_OWNER,component:'theme-gallery-mode',source:STYLE_SOURCE});else StyleGate.set(section,property,value,{owner:STYLE_OWNER,component:'theme-gallery-mode',kind:'runtime-inline',source:STYLE_SOURCE});}delete section.dataset.galleryStyle;}
    for(const swatch of root?.querySelectorAll?.('[data-gallery-swatch]')||[]){const index=Math.max(0,Number(swatch.dataset.gallerySwatch)||0);StyleGate.set(swatch,'background',`var(--dkds-gallery-series-${index})`,{owner:STYLE_OWNER,component:'theme-gallery-swatch',kind:'runtime-inline',source:STYLE_SOURCE});}
  }
  function annotate(root){
    window.DKDSSemanticUI?.assign?.(root);
    for(const row of root.querySelectorAll('[data-gallery-meta]')){const component=row.dataset.component,target=row.closest('.dkds-theme-gallery-demo')?.querySelector?.(`[data-dkds-component-identity="${component}"]`),inspection=target?window.DKDSThemeComponentAppearance?.inspect?.(target):null,surface=inspection?.resolved?.surface;row.textContent=surface?`${inspection.componentIdentity}.${surface.slot} · ${surface.path} → ${surface.value||surface.fallback||'Core fallback'}`:`${component} · UNMANAGED_COMPONENT_APPEARANCE`;}
  }
  function parityReport(root=document){
    const gallery=document.querySelector('.dkds-theme-gallery-overlay'),rows=[];if(!gallery)return Object.freeze({status:'NOT_PRESENT',rows:Object.freeze([]),ok:false});
    for(const def of window.DKDSSemanticUI?.components?.()||[]){const galleryEl=gallery.querySelector(`[data-dkds-component-identity="${def.id}"]`),realEl=[...root.querySelectorAll?.(`[data-dkds-component-identity="${def.id}"]`)||[]].find(el=>!el.closest('.dkds-theme-gallery-overlay'))||null;if(!galleryEl||!realEl){rows.push(Object.freeze({component:def.id,status:'NOT_PRESENT',gallery:!!galleryEl,real:!!realEl}));continue;}const a=window.DKDSThemeComponentAppearance.inspect(galleryEl),b=window.DKDSThemeComponentAppearance.inspect(realEl),gallerySlot=a.resolved?.surface?.path||'',realSlot=b.resolved?.surface?.path||'',status=gallerySlot===realSlot&&a.componentIdentity===b.componentIdentity?'MANAGED':'WRONG_COMPONENT_IDENTITY';rows.push(Object.freeze({component:def.id,status,gallerySlot,realSlot,galleryIdentity:a.componentIdentity,realIdentity:b.componentIdentity}));}
    const failures=rows.filter(row=>row.status==='WRONG_COMPONENT_IDENTITY');return Object.freeze({status:failures.length?'WRONG_COMPONENT_IDENTITY':'MANAGED',rows:Object.freeze(rows),ok:failures.length===0});
  }
  function open(profileId){
    document.querySelector('.dkds-theme-gallery-overlay')?.remove();const id=profileId||window.DKDSTheme?.profile?.()||'builtin.default',coverage=window.DKDSTheme?.coverage?.()||{summary:{}},cov=coverage.summary||{},coverageText=`Material ${cov.managed||0}/${cov.areas||0}${cov.notPresentAreas?` · NOT_PRESENT ${cov.notPresentAreas}`:''} · Components ${cov.managedComponents||0}/${cov.presentComponentTypes||0} · unused ${cov.authoredUnused||0}`;
    const overlay=document.createElement('div');overlay.className='dkds-theme-gallery-overlay';overlay.innerHTML=`<div class="dkds-theme-gallery-dialog"><div class="dkds-theme-gallery-head"><div><strong>Theme Component Gallery</strong><span>Theme Contract ${window.DKDSTheme?.contractVersion||'?'} · ${escapeHtml(id)} · ${coverageText}</span></div><button class="dkds-theme-gallery-close dkds-panel-close-button" aria-label="关闭">×</button></div><div class="dkds-theme-gallery-panes">${panel(id,'light')}${panel(id,'dark')}</div></div>`;document.body.appendChild(overlay);applyGalleryRuntimeStyles(overlay);annotate(overlay);overlay.querySelector('.dkds-theme-gallery-close').onclick=()=>overlay.remove();overlay.addEventListener('click',event=>{if(event.target===overlay)overlay.remove();});return overlay;
  }
  window.DKDSThemeGallery=Object.freeze({version:VERSION,open,parityReport,annotate});
})();
