(() => {
  function create(ctx,spec={}){
    const D=ctx.data.model,controller=spec.controller,query=spec.query,currentOutputArtifact=spec.currentOutputArtifact,getState=spec.getState,page=spec.page;
    if(!D||typeof query!=='function'||typeof currentOutputArtifact!=='function'||typeof getState!=='function')throw new Error('Data Center chart runtime requires model/query/artifact/state adapters.');
    const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const chartSchema={fields:[{id:'x',type:'column',label:'X 列',required:true},{id:'ys',type:'columns',label:'Y 列',required:true},{id:'mode',type:'select',label:'绘图模式',default:'lines+markers',options:[{value:'lines',label:'折线'},{value:'markers',label:'散点'},{value:'lines+markers',label:'折线 + 点'}]},{id:'showLegend',type:'boolean',label:'显示图例',default:true}]};
    ctx.charts.register('xy-line',{name:'XY 多序列图',description:'通用 DataTable X/Y 折线或散点图。',inputKinds:['data.table'],parameterSchema:chartSchema,render({container,artifact,parameters}){
      const x=D.column(artifact,parameters.x);if(!x)throw new Error(`未找到 X 列 ${parameters.x}`);const ys=(parameters.ys||[]).map(k=>D.column(artifact,k)).filter(Boolean);if(!ys.length)throw new Error('至少选择一个 Y 列。');
      const artifactRevision=ctx.data.artifacts.artifactRevision(artifact.id),traces=ys.map(y=>({x:x.values,y:y.values,mode:parameters.mode||'lines+markers',name:y.name,artifactId:artifact.id,artifactRevision,seriesId:D.seriesId(artifact,y.key),...(Array.isArray(artifact.rowIds)?{rowIds:artifact.rowIds}:{rowIdAt:index=>D.rowId(artifact,index)}),hovertemplate:`${esc(x.name)}=%{x}<br>${esc(y.name)}=%{y}<extra>${esc(y.name)}</extra>`}));
      return ctx.ui.scientificPlot.react(container,traces,{margin:{l:72,r:22,t:30,b:62},xaxis:{title:`${x.name}${x.unit?` (${x.unit})`:''}`,automargin:true},yaxis:{title:ys.length===1?`${ys[0].name}${ys[0].unit?` (${ys[0].unit})`:''}`:'Value',automargin:true},legend:{orientation:'h',y:1.08},showlegend:parameters.showLegend!==false,hovermode:'closest',autosize:true},{responsive:true,displaylogo:false,scrollZoom:true},{interaction:controller?.interaction,source:'data-center-chart',renderKey:`data-center:${artifact.id}:${artifactRevision}:${JSON.stringify(parameters||{})}`,legendPolicy:{link:true,linkGroup:`data-center:${artifact.id}:legend`},traceEntity:(trace,index)=>{const y=ys[index];if(!y)return {id:artifact.id,type:'data-center.artifact',label:artifact.name};const ref=ctx.ui.selection.refs.series(artifact.id,D.seriesId(artifact,y.key),{artifactRevision});return {id:`data-center.column:${artifact.id}:${y.key}`,type:'data-center.column',parents:[artifact.id],label:y.name,ref,metadata:{columnId:String(y.key),name:y.name,unit:y.unit,role:y.role}};}});
    }});
    let panel=null,renderRevision=0;
    const providers=()=>{const a=currentOutputArtifact();return ctx.charts.list().filter(p=>!p.inputKinds?.length||!a||p.inputKinds.includes(a.kind));};
    function clearPreview(message='选择 DataTable 后可配置图形。'){
      renderRevision+=1;const host=query('#dcChart');if(!host)return false;try{ctx.ui.scientificPlot.purge?.(host);}catch{}try{ctx.ui.scientificPlot.get?.(host)?.dispose?.();}catch{}host.replaceChildren();if(message)ctx.ui.dom.html(host,`<div class="empty-state">${esc(message)}</div>`);return true;
    }
    function renderParams(){
      const state=getState(),a=currentOutputArtifact();panel?.destroy?.();const provider=ctx.charts.list().find(x=>x.id===query('#dcChartProvider')?.value);
      if(!provider||!a||a.kind!=='data.table'){const host=query('#dcChartParams');if(host)ctx.ui.dom.html(host,'<div class="empty-state">选择 DataTable 后可配置图形。</div>');clearPreview();return;}
      state.chart.provider=provider.id;const defaults={...ctx.parameters.defaults(provider.parameterSchema||{fields:[]},state.chart.parameters||{})},validKeys=new Set((a.columns||[]).map(c=>String(c.key)));if(!validKeys.has(String(defaults.x||'')))defaults.x=a.columns.find(c=>c.role==='x')?.key||a.columns[0]?.key||'';defaults.ys=(Array.isArray(defaults.ys)?defaults.ys:[]).filter(key=>validKeys.has(String(key)));if(!defaults.ys.length)defaults.ys=[a.columns.find(c=>c.role==='y'&&c.key!==defaults.x)?.key||a.columns.find(c=>c.key!==defaults.x)?.key].filter(Boolean);
      panel=(spec.mountParameterForm||ctx.parameters.render)(query('#dcChartParams'),provider.parameterSchema||{fields:[]},{value:defaults,context:{table:a},compact:true,autoFit:true,layoutOwner:'host',onChange:value=>{state.chart.parameters=value;spec.onStateChange?.('chart-parameters');schedule('parameter-change');}});state.chart.parameters=panel.getValue();
    }
    function renderControls(){const state=getState(),rows=providers(),select=query('#dcChartProvider');if(!select)return;ctx.ui.dom.html(select,rows.map(p=>`<option value="${esc(p.id)}">${esc(p.name||p.id)}</option>`).join(''));if(rows.some(p=>p.id===state.chart.provider))select.value=state.chart.provider;else state.chart.provider=select.value||'';select.hidden=rows.length<=1;select.title=rows.length>1?'切换 Chart Provider':'';renderParams();}
    async function render({silent=false}={}){const state=getState(),a=currentOutputArtifact(),select=query('#dcChartProvider'),provider=ctx.charts.list().find(x=>x.id===select?.value);if(!a||!provider||a.kind!=='data.table'){clearPreview();return false;}const valid=panel?.validate?.();if(valid&&!valid.ok){if(!silent)ctx.status.set('图形参数存在错误。');return false;}state.chart.parameters=panel?.getValue?.()||state.chart.parameters||{};const revision=++renderRevision;try{await Promise.resolve(provider.render({container:query('#dcChart'),artifact:a,parameters:state.chart.parameters,context:{page:page?.()||null}}));if(revision!==renderRevision)return false;ctx.ui.dom.frame(()=>resize());return true;}catch(err){if(revision!==renderRevision)return false;const host=query('#dcChart');if(host&&!ctx.ui.dom.query('.dkds-scientific-chart-host',host))ctx.ui.dom.html(host,`<div class="empty-state">图形预览失败：${esc(err?.message||err)}</div>`);ctx.status.set(`绘图失败：${err?.message||err}`);return false;}}
    function schedule(reason='auto'){const revision=++renderRevision;ctx.ui.dom.frame(()=>{if(revision!==renderRevision)return;void render({silent:reason!=='manual'});});}
    function resize(){try{ctx.ui.scientificPlot.resize(query('#dcChart'));}catch{}}
    function setProvider(value){const state=getState();state.chart.provider=String(value??'');const select=query('#dcChartProvider');if(select)select.value=state.chart.provider;renderParams();spec.onStateChange?.('chart-provider');schedule('domain-provider-change');return true;}
    function setParameters(value){const state=getState();state.chart.parameters=D.deepClone(value||{});panel?.setValue?.(state.chart.parameters);spec.onStateChange?.('chart-parameters');schedule('domain-parameter-change');return true;}
    function dispose(){renderRevision+=1;panel?.destroy?.();panel=null;try{ctx.ui.scientificPlot.get?.(query('#dcChart'))?.dispose?.();}catch{}}
    return Object.freeze({providers,renderControls,renderParams,render,schedule,resize,setProvider,setParameters,dispose});
  }
  window.DKDSPluginModules.define('builtin.data-center','chart-runtime',Object.freeze({create}));
})();
