(() => {
  const manifest={"id":"com.dkds.transfer-vth-lab","name":"Transfer Curve Vth Lab","version":"3.3.4","apiVersion":"1.19.0","entry":"plugin.js","scripts":["analysis-runtime.js","live-domain.js","domain-adapter.js","unit-presentation.js","plugin.js"],"styles":[],"enabled":true,"order":420,"description":"Built-in threshold-voltage extraction TOP workbench using scoped project sources, Core-owned import and bounded ScientificPlot layout.","pluginType":"workbench","requiresCore":["runtime","modules","events","services","status","state","project","workspace","data.model","data.types","data.sources","data.artifacts","analysis.algorithms","ui.dom","ui.workspace","ui.scientific-plot","ui.table","ui.settings","ui.actions","ui.interaction-behavior","ui.activities","ui.top-workspace","ui.pages","execution.tasks","execution.commands","ui.unit-templates"],"capabilities":["analysis.threshold-voltage","ui.page","ui.interaction-behavior","ui.scientific-plot","ui.batch-results","data.scoped-sources","ui.top-workspace","ui.plugin-workspace","ui.unit-templates"],"workspace":{"role":"top","activity":"transfer-vth-lab","icon":"Vₜ","title":"Vth 工作台"},"window":{"activity":"transfer-vth-lab","title":"Vth 工作台","width":1420,"height":900,"minWidth":900,"minHeight":620,"dependencies":["scientific-renderer","data-model"],"prewarm":false,"reuse":true,"persistence":"project","artifactHydration":"live"},"data":{"accepts":["science.transport.iv","science.transport.transfer"]},"algorithmProvider":true,"algorithmCategories":["transfer-curve"],"algorithmProvides":[{"category":"transfer-curve","id":"transfer.vth-constant-current","version":"2.0.0","title":"Threshold voltage by constant-current neighborhood"}],"pluginDependencies":[{"id":"builtin.scientific-data-contracts"}],"platformPresentation":{"desktop":{"mode":"shared"},"mobile":{"mode":"adaptive"}},"tasks":[{"id":"analyze-vth","entry":"vth-task.js","imports":["analysis-runtime.js"]}]};
  DKDSPlugins.define(manifest, async ctx => {
    const Analysis=ctx.modules.require('analysis-runtime');
    const LiveDomain=ctx.modules.require('live-domain');
    const {finite,num,clone,defaults,pointsOfArtifact}=Analysis;
    const analyzeTask=(curve,parameters,manualWindow,key)=>ctx.tasks.submit('analyze-vth',{curve,parameters,manualWindow},{key,latest:true}).promise;
    const dom=ctx.ui.dom;
    const escape=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));

    ctx.analysis.algorithms.register('transfer.vth-constant-current',{version:'2.0.0',category:'transfer-curve',title:'Threshold voltage by constant-current neighborhood',default:true,parameterSchema:{fields:[{id:'method',type:'select',label:'方法',default:'linear-window',options:['linear-window','interpolation']},{id:'branch',type:'select',label:'扫描段',default:'auto',options:['auto','first','second','all']},{id:'targetCurrent',type:'number',label:'目标电流 / A',default:4e-10},{id:'lowCurrent',type:'number',label:'拟合下限 / A',default:2e-10},{id:'highCurrent',type:'number',label:'拟合上限 / A',default:2e-9},{id:'absoluteCurrent',type:'boolean',label:'使用 |I|',default:true}]},run(input,{parameters={},manualWindow=null}={}){const curve={points:Array.isArray(input?.points)?input.points:pointsOfArtifact(input)};return analyzeTask(curve,{...defaults(),...parameters},manualWindow,`provider:${String(input?.id||'curve')}`);}});
    ctx.data.types.register('analysis.threshold-voltage',{title:'Threshold-voltage extraction result',parents:['result.analysis'],kind:'result',key:v=>v?.curveId?`${v.curveId}:${v.method||'vth'}`:undefined});

    const analysisDefaultKeys=Object.freeze(['method','branch','targetCurrent','lowCurrent','highCurrent','absoluteCurrent']);
    const settings=ctx.ui.settings.define('defaults',{title:'Vth 工作台默认设置',description:'仅影响新建或重置工程的分析参数；不会修改当前工程、数据图显示方式或界面样式。',defaults:Object.fromEntries(analysisDefaultKeys.map(key=>[key,defaults()[key]])),fields:[{id:'method',label:'默认方法',type:'select',options:[{value:'linear-window',label:'恒流邻域线性回归'},{value:'interpolation',label:'恒流插值'}]},{id:'branch',label:'默认扫描段',type:'select',options:[{value:'auto',label:'自动'},{value:'first',label:'第一扫描段'},{value:'second',label:'第二扫描段'},{value:'all',label:'全部数据'}]},{id:'targetCurrent',label:'默认目标电流 / A',type:'number'},{id:'lowCurrent',label:'默认拟合下限 / A',type:'number'},{id:'highCurrent',label:'默认拟合上限 / A',type:'number'},{id:'absoluteCurrent',label:'默认使用 |I|',type:'boolean'}]});
    const projectDefaultParameters=()=>{const saved=settings.get()||{},analysisDefaults={};for(const key of analysisDefaultKeys)if(saved[key]!==undefined)analysisDefaults[key]=saved[key];return{...defaults(),...analysisDefaults};};
    const initialState=()=>({schema:3,parameters:projectDefaultParameters(),selectedCurveId:null,manualWindows:{},view:null});
    const state=ctx.state.create(initialState());
    ctx.project.registerSlice('workspace',{serialize:()=>clone(state.get()),restore:data=>{if(!data||typeof data!=='object')return;const base=initialState();state.set({...base,...data,parameters:{...base.parameters,...(data.parameters||{})},manualWindows:data.manualWindows&&typeof data.manualWindows==='object'?data.manualWindows:{}});},reset:()=>state.set(initialState())});
    const offSettings=settings.subscribe((_value,meta={})=>{ctx.status.set(meta?.reset?'Vth 默认分析参数已恢复内置值；当前工程与界面保持不变，新建或重置工程后生效。':'Vth 默认分析参数已保存；当前工程与界面保持不变，新建或重置工程后生效。');});

    let curves=[],sourceMode='empty',workbench=null,plotSurface=null,tableSurface=null,root=null,main=null,left=null,plotTarget=null,controls={},metrics={},analysisRevision=0,liveDomain=null,liveStateOff=null,presentation=null;
    const resultCache=new Map(),resultPending=new Map();
    function invalidateResults(reason='inputs'){analysisRevision+=1;resultCache.clear();resultPending.clear();ctx.tasks.cancelAll?.(`vth-${reason}`);}
    function queueResult(curve){if(!curve)return null;const revision=analysisRevision,key=`${revision}:${curve.id}`;if(resultCache.has(key)||resultPending.has(key))return null;const parameters={...state.get().parameters},manualWindow=state.get().manualWindows?.[curve.id]||null;const promise=analyzeTask(curve,parameters,manualWindow,`curve:${curve.id}`).then(value=>{if(revision===analysisRevision){resultCache.set(key,value);dom.microtask(()=>renderAll('analysis-result'));liveDomain?.notify?.('analysis-result',{curveId:curve.id,revision});}return value;}).catch(err=>{if(err?.name!=='AbortError'&&revision===analysisRevision){resultCache.set(key,{ok:false,status:String(err?.message||err)});dom.microtask(()=>renderAll('analysis-error'));liveDomain?.notify?.('analysis-error',{curveId:curve.id,revision,message:String(err?.message||err)});}return null;}).finally(()=>resultPending.delete(key));resultPending.set(key,promise);return promise;}
    function demoCurve(){const points=[];for(const [a,b,shift,label] of [[-2,2,0,'first'],[2,-2,.14,'second']])for(let i=0;i<100;i++){const x=a+(b-a)*i/99,center=.42+shift,current=2e-12+1.3e-9*Math.exp((x-center)*3.4);points.push({x,y:Math.min(current,8e-8),segment:label});}return{id:'demo-transfer',name:'示例 · 双向转移曲线',points,artifactId:'',source:{kind:'demo'}};}
    function sourceDescriptors(){const rows=ctx.data.sources.list();return Array.isArray(rows)?rows:[];}
    function loadAssignedCurves(){const out=[];for(const descriptor of sourceDescriptors()){if(descriptor?.excluded)continue;const artifact=ctx.data.artifacts.get(descriptor.artifactId);const points=pointsOfArtifact(artifact);if(points.length>=2)out.push({id:String(artifact?.id||descriptor.artifactId),artifactId:String(descriptor.artifactId||artifact?.id||''),name:String(descriptor.name||artifact?.name||descriptor.artifactId),points,source:descriptor});}return out;}
    function selected(){const id=state.get().selectedCurveId;return curves.find(c=>c.id===id)||curves[0]||null;}
    function resultFor(curve){if(!curve)return null;const key=`${analysisRevision}:${curve.id}`;if(resultCache.has(key))return resultCache.get(key);queueResult(curve);return null;}
    function currentResult(){return resultFor(selected());}
    function displayY(v){const p=state.get().parameters,raw=Number(v);return p.absoluteCurrent!==false?Math.abs(raw):raw;}
    function inverseDisplayY(v){return Number(v);}
    function yTitle(){const p=state.get().parameters;return p.absoluteCurrent!==false?'|I| (A)':'I (A)';}
    function fmt(v,d=5){if(!finite(v))return'—';const n=Number(v),a=Math.abs(n);return a&&((a>=1e4)||(a<1e-3))?n.toExponential(Math.max(2,d-1)):n.toPrecision(d);}
    function plotCurves(){const active=selected(),p=state.get().parameters,rows=p.showAllCurves?curves:(active?[active]:[]);const traces=rows.map(c=>({id:`data:${c.id}`,entityId:c.id,points:c.points,strokeWidth:c.id===active?.id?2.3:1.2,opacity:c.id===active?.id?1:.32,source:{curveId:c.id,role:'data'}}));const r=currentResult();if(active&&r?.ok&&r.method==='linear-window'&&finite(r.slope)&&finite(r.intercept)&&r.fitWindow){const [a,b]=r.fitWindow;traces.push({id:'fit-line',points:[{x:a,y:r.slope*a+r.intercept},{x:b,y:r.slope*b+r.intercept}],dash:'7 4',strokeWidth:2,source:{role:'fit'}});}return traces;}
    function plotManipulators(){const curve=selected(),r=currentResult();if(!curve||!r?.ok)return[];const out=[];if(r.fitWindow)out.push({id:'fit-window',kind:'range',axis:'x',geometry:{start:r.fitWindow[0],end:r.fitWindow[1]},constraints:{minSpan:1e-12},presentation:{band:true}});if(finite(r.targetCurrent))out.push({id:'target-current',kind:'axis',axis:'y',geometry:{value:displayY(r.targetCurrent)}});return out;}
    function patchParameters(patch,reason='parameters'){const before=state.get().parameters,parameters={...before,...patch};if(parameters.absoluteCurrent===false)parameters.logY=false;const scaleChanged=parameters.logY!==before.logY||parameters.absoluteCurrent!==before.absoluteCurrent;state.patch({parameters});invalidateResults('parameters');if(scaleChanged&&plotTarget)createPlotSurface();renderAll(reason);ctx.project.capture();}
    function applyManualWindow(window){const curve=selected();if(!curve||!Array.isArray(window)||window.length<2)return;const a=num(window[0]),b=num(window[1]);if(!finite(a)||!finite(b))return;state.patch({manualWindows:{...state.get().manualWindows,[curve.id]:[Math.min(a,b),Math.max(a,b)]}});invalidateResults('manual-window');renderAll('fit-window');ctx.project.capture();}
    function refreshSources({announce=false}={}){invalidateResults('sources');const loaded=loadAssignedCurves();if(loaded.length){curves=loaded;sourceMode='project';const saved=state.get().selectedCurveId;state.patch({selectedCurveId:curves.some(c=>c.id===saved)?saved:curves[0].id});if(announce)ctx.status.set(`Vth 工作台已同步 ${curves.length} 条已分配转移曲线`);}else{curves=[];sourceMode='empty';state.patch({selectedCurveId:null});if(announce)ctx.status.set('当前 Vth 工作台没有已分配数据；请使用顶部“导入数据”。');}renderAll('sources');return loaded.length;}
    function loadDemo(){invalidateResults('demo');curves=[demoCurve()];sourceMode='demo';state.patch({selectedCurveId:curves[0].id,manualWindows:{}});renderAll('demo');ctx.status.set('已载入 Vth 示例双向转移曲线');}
    function renderControls(){if(!controls.curve)return;const active=selected();dom.html(controls.curve,curves.length?curves.map(c=>`<option value="${escape(c.id)}">${escape(c.name)}</option>`).join(''):'<option value="">未分配数据</option>');controls.curve.value=active?.id||'';const p=state.get().parameters;for(const [key,el] of Object.entries(controls)){if(!el||key==='curve')continue;if(el.type==='checkbox')el.checked=!!p[key];else if(Object.prototype.hasOwnProperty.call(p,key))el.value=String(p[key]);}const badge=presentation?.sourceBadge;if(badge)badge.textContent=sourceMode==='project'?`${curves.length} 组工程数据`:sourceMode==='demo'?'示例数据':'等待导入';}
    function renderMetrics(){const r=currentResult(),curve=selected();metrics.vth.textContent=r?.ok?`${fmt(r.vth,7)} V`:'—';metrics.branch.textContent=r?.branch||'—';metrics.r2.textContent=r?.ok&&finite(r.r2)?Number(r.r2).toFixed(6):(r?.method==='interpolation'?'插值':'—');metrics.n.textContent=r?.n!=null?String(r.n):'—';const title=presentation?.plotHeader?.title;if(title)title.textContent=curve?.name||'转移曲线';const status=presentation?.plotHeader?.meta;if(status)status.textContent=r?(r.ok?`${r.method==='linear-window'?'线性回归':'插值'} · ${r.status}`:r.status):'未加载数据';}
    function renderTable(){if(!tableSurface)return;const rows=curves.map(c=>{const r=resultFor(c);return{curve:c.name,branch:r?.branch||'',vth:r?.ok?fmt(r.vth,8):'—',r2:r?.ok&&finite(r.r2)?Number(r.r2).toFixed(6):'',n:r?.n??'',status:r?.status||''};});tableSurface.setData([{key:'curve',label:'曲线'},{key:'branch',label:'扫描段'},{key:'vth',label:'Vth / V'},{key:'r2',label:'R²'},{key:'n',label:'N'},{key:'status',label:'状态'}],rows);}
    function renderPlot(reason='render'){if(!plotSurface||!plotTarget)return;plotSurface.requestRender(reason);}
    function renderAll(reason='render'){if(!root)return;renderControls();renderMetrics();renderTable();renderPlot(reason);}

    const liveParameterKeys=new Set(['method','branch','targetCurrent','lowCurrent','highCurrent','absoluteCurrent','logY','showAllCurves']);
    const liveNumericParameterKeys=new Set(['targetCurrent','lowCurrent','highCurrent']);
    const cachedResult=curve=>curve?resultCache.get(`${analysisRevision}:${curve.id}`)||null:null;
    async function awaitResult(curve){if(!curve)return null;const cached=cachedResult(curve);if(cached)return cached;resultFor(curve);const pending=resultPending.get(`${analysisRevision}:${curve.id}`);if(pending)await pending;return cachedResult(curve);}
    async function analyzeAllLive(){const rows=[];for(const curve of curves)rows.push({curveId:curve.id,result:await awaitResult(curve)});return rows;}
    function selectCurveLive(payload={}){const id=String(payload?.value??payload?.curveId??payload??'');if(!id||!curves.some(curve=>curve.id===id))return false;state.patch({selectedCurveId:id},{reason:'live-selected-curve'});renderAll('live-selected-curve');ctx.project.capture();return true;}
    function setParameterLive(payload={}){const key=String(payload?.key||'');if(!liveParameterKeys.has(key))throw new Error(`Vth live parameter unavailable: ${key||'(empty)'}`);let value=payload?.value;if(liveNumericParameterKeys.has(key))value=num(value,state.get().parameters[key]);else if(['absoluteCurrent','logY','showAllCurves'].includes(key))value=!!value;else value=String(value??state.get().parameters[key]);patchParameters({[key]:value},`live:${key}`);return state.get().parameters[key];}
    function setParametersLive(payload={}){const source=payload?.value&&typeof payload.value==='object'?payload.value:payload;const patch={};for(const [key,raw] of Object.entries(source&&typeof source==='object'?source:{})){if(!liveParameterKeys.has(key))continue;patch[key]=liveNumericParameterKeys.has(key)?num(raw,state.get().parameters[key]):(['absoluteCurrent','logY','showAllCurves'].includes(key)?!!raw:String(raw));}if(Object.keys(patch).length)patchParameters(patch,'live:parameters');return clone(state.get().parameters);}
    function resetManualWindow(){const curve=selected();if(!curve)return false;const next={...state.get().manualWindows};delete next[curve.id];state.patch({manualWindows:next},{reason:'reset-window'});invalidateResults('reset-window');renderAll('reset-window');ctx.project.capture();return true;}
    function setViewLive(payload={}){const value=payload&&Object.prototype.hasOwnProperty.call(payload,'value')?payload.value:payload;state.patch({view:value&&typeof value==='object'?clone(value):null},{reason:'live-view'});renderPlot('live-view');ctx.project.capture();return clone(state.get().view);}
    function livePresentation(){const active=selected(),result=cachedResult(active),parameters=state.get().parameters;const curveRows=curves.map(curve=>{const row=cachedResult(curve);return{curve:curve.name,branch:row?.branch||'',vth:row?.ok?fmt(row.vth,8):'—',r2:row?.ok&&finite(row.r2)?Number(row.r2).toFixed(6):'',n:row?.n??'',status:row?.status||''};});const plotRows=(parameters.showAllCurves?curves:(active?[active]:[])).map(curve=>({id:`data:${curve.id}`,entityId:curve.id,points:clone(curve.points),strokeWidth:curve.id===active?.id?2.3:1.2,opacity:curve.id===active?.id?1:.32,source:{curveId:curve.id,role:'data'}}));if(active&&result?.ok&&result.method==='linear-window'&&finite(result.slope)&&finite(result.intercept)&&result.fitWindow){const [a,b]=result.fitWindow;plotRows.push({id:'fit-line',points:[{x:a,y:result.slope*a+result.intercept},{x:b,y:result.slope*b+result.intercept}],dash:'7 4',strokeWidth:2,source:{role:'fit'}});}const manipulators=[];if(active&&result?.ok){if(result.fitWindow)manipulators.push({id:'fit-window',kind:'range',axis:'x',geometry:{start:result.fitWindow[0],end:result.fitWindow[1]},constraints:{minSpan:1e-12},presentation:{band:true}});if(finite(result.targetCurrent))manipulators.push({id:'target-current',kind:'axis',axis:'y',geometry:{value:displayY(result.targetCurrent)}});}return{metrics:{vth:result?.ok?`${fmt(result.vth,7)} V`:'—',branch:result?.branch||'—',r2:result?.ok&&finite(result.r2)?Number(result.r2).toFixed(6):(result?.method==='interpolation'?'插值':'—'),n:result?.n!=null?String(result.n):'—'},plot:{title:active?.name||'转移曲线',status:result?(result.ok?`${result.method==='linear-window'?'线性回归':'插值'} · ${result.status}`:result.status):'未加载数据',xTitle:'Gate voltage (V)',yTitle:yTitle(),yScaleType:(parameters.logY&&parameters.absoluteCurrent!==false)?'log':'linear',curves:plotRows,manipulators,view:clone(state.get().view||{})},tableRows:curveRows};}
    function liveSnapshot(){const current=selected();return{schema:1,sourceMode,curves:curves.map(curve=>({id:curve.id,artifactId:curve.artifactId||'',name:curve.name,points:clone(curve.points),result:clone(cachedResult(curve))})),selectedCurveId:state.get().selectedCurveId,selectedCurve:current?{id:current.id,artifactId:current.artifactId||'',name:current.name}:null,state:clone(state.get()),result:clone(cachedResult(current)),presentation:livePresentation()};}

    function captureVthCommandArgs(payload={}){const current=selected(),artifactId=String(payload?.artifactId||current?.artifactId||'');if(!artifactId)throw new Error('Vth 可重放分析需要已分配的工程 Artifact。');const parameters={...state.get().parameters,...((payload?.parameters&&typeof payload.parameters==='object')?payload.parameters:{})};const manualWindow=Array.isArray(payload?.manualWindow)?payload.manualWindow:(state.get().manualWindows?.[current?.id]||null);return{artifactId,parameters,manualWindow:Array.isArray(manualWindow)?[num(manualWindow[0]),num(manualWindow[1])]:null};}
    async function analyzeArtifactCommand({artifactId,parameters,manualWindow}){const artifact=ctx.data.artifacts.get(String(artifactId||''));if(!artifact)throw new Error(`Vth 输入 Artifact 不存在：${artifactId}`);const points=pointsOfArtifact(artifact);if(points.length<2)throw new Error('Vth 输入 Artifact 不包含足够的有效转移曲线点。');const result=await analyzeTask({id:String(artifact.id||artifactId),points},{...defaults(),...(parameters||{})},manualWindow,`command:${artifactId}`);ctx.status.set(result?.ok?`Vth 分析完成：${fmt(result.vth,7)} V`:`Vth 分析完成：${result?.status||'无有效结果'}`);return result;}

    ctx.commands.register('com.dkds.transfer-vth-lab.analyze-artifact',analyzeArtifactCommand,{domainCommand:{domain:'analysis.threshold-voltage',version:'1.0.0',title:'Vth 恒流邻域分析',replayable:true,inputSchema:{type:'object',properties:{artifactId:{type:'string'},parameters:{type:'object'},manualWindow:{type:'array',minItems:2,maxItems:2,items:{type:'number'}}},additionalProperties:false},captureArgs:captureVthCommandArgs,inputs:args=>[{artifactId:args.artifactId,role:'transfer-curve'}],algorithm:()=>({category:'transfer-curve',id:'transfer.vth-constant-current',version:'2.0.0',provider:`${ctx.manifest.id}@${ctx.manifest.version}`}),parameters:args=>({...args.parameters,manualWindow:args.manualWindow}),outputs:()=>[]}});
    ctx.commands.register('com.dkds.transfer-vth-lab.refresh',()=>refreshSources({announce:true}));
    ctx.commands.register('com.dkds.transfer-vth-lab.demo',()=>loadDemo());
    ctx.commands.register('com.dkds.transfer-vth-lab.fit-view',()=>plotSurface?.fitToData?.({source:'vth-command'})??false);
    ctx.commands.register('com.dkds.transfer-vth-lab.reset-window',()=>resetManualWindow());
    ctx.ui.interactionBehaviors.create('transfer-vth-lab-keys',{activity:'transfer-vth-lab',bindings:[{gesture:'key',target:'keyboard',chord:'Ctrl+Enter',command:'com.dkds.transfer-vth-lab.analyze-artifact'},{gesture:'key',target:'keyboard',chord:'Ctrl+R',command:'com.dkds.transfer-vth-lab.refresh'},{gesture:'key',target:'keyboard',chord:'Ctrl+0',command:'com.dkds.transfer-vth-lab.fit-view'},{gesture:'key',target:'keyboard',chord:'Ctrl+Shift+R',command:'com.dkds.transfer-vth-lab.reset-window'}]});

    ctx.ui.activities.add({id:'transfer-vth-lab',label:'Vth 工作台',contextLabel:'Vth 工作台',icon:'Vₜ',order:50,primary:true,openMode:'window',artifactHydration:'live',description:'转移曲线阈值电压提取',onActivate:()=>{ctx.workspace.openPage('transferVthLabPage');refreshSources({announce:false});}});
    const page=ctx.ui.pages.add({id:'transfer-vth-lab-page',pageId:'transferVthLabPage',label:'Vth 工作台',title:'Transfer Curve Vth Lab',order:50,toolbar:false,activity:'transfer-vth-lab',className:'transfer-vth-lab-page',html:''});
    const UnitPresentation=ctx.modules.require('unit-presentation');
    presentation=UnitPresentation.mount(ctx,page,{
      refresh:()=>ctx.commands.run('com.dkds.transfer-vth-lab.refresh'),
      demo:()=>ctx.commands.run('com.dkds.transfer-vth-lab.demo'),
      fitView:()=>ctx.commands.run('com.dkds.transfer-vth-lab.fit-view'),
      openSettings:()=>settings.open()
    });
    workbench=presentation.workbench;root=workbench.shell||presentation.workspaceHost;plotTarget=presentation.plotTarget;controls=presentation.controls;metrics=presentation.metrics;tableSurface=presentation.tableSurface;
    function createPlotSurface(){
      plotSurface=presentation.createPlotSurface({xTitle:'Gate voltage (V)',yTitle:yTitle(),yScaleType:(state.get().parameters.logY&&state.get().parameters.absoluteCurrent!==false)?'log':'linear',xValue:p=>num(p?.x),yValue:p=>displayY(p?.y),navigationTools:true,legend:{enabled:true,placement:'top',maxRows:2},renderPriority:'frame',activity:'transfer-vth-lab',interactionExtensions:[{id:'vth.shift-select-region',gesture:'box',target:'background',modifiers:['shift'],intent:'select-region',priority:30}],getCurves:()=>plotCurves(),getMarkers:()=>[],getManipulators:()=>plotManipulators(),getView:()=>state.get().view||{},setView:view=>state.patch({view},{reason:'plot-view'}),showMarkers:()=>true,onCurveSelect:payload=>{const id=payload?.curve?.source?.curveId||payload?.curve?.entityId||String(payload?.curve?.id||'').replace(/^data:/,'');if(id&&curves.some(c=>c.id===id)){state.patch({selectedCurveId:id});renderAll('curve-select');ctx.project.capture();}},onManipulationCommit:payload=>{if(payload?.manipulator?.id==='fit-window'){const g=payload.geometry||{};applyManualWindow([g.start,g.end]);}else if(payload?.manipulator?.id==='target-current'){const value=inverseDisplayY(payload?.geometry?.value);if(finite(value))patchParameters({targetCurrent:value},'target-current');}},onManipulationReset:payload=>{if(payload?.manipulator?.id==='fit-window')ctx.commands.run('com.dkds.transfer-vth-lab.reset-window');},onRangeSelect:payload=>{const values=[payload?.x0,payload?.x1,payload?.range?.x0,payload?.range?.x1,payload?.range?.[0],payload?.range?.[1]].filter(finite).map(Number);if(values.length>=2)applyManualWindow([values[0],values[1]]);},onReset:()=>state.patch({view:null})});
      return plotSurface;
    }
    createPlotSurface();
    dom.on(controls.curve,'change',()=>{state.patch({selectedCurveId:controls.curve.value||null});renderAll('curve');ctx.project.capture();});
    for(const key of ['method','branch'])dom.on(controls[key],'change',()=>patchParameters({[key]:controls[key].value},key));
    for(const key of ['targetCurrent','lowCurrent','highCurrent'])dom.on(controls[key],'change',()=>patchParameters({[key]:num(controls[key].value,state.get().parameters[key])},key));
    for(const key of ['absoluteCurrent','logY','showAllCurves'])dom.on(controls[key],'change',()=>patchParameters({[key]:controls[key].checked},key));
    ctx.ui.topWorkspace.register({id:'transfer-vth-lab',activity:'transfer-vth-lab',label:'Vth 工作台',icon:'Vₜ',layout:{mode:'native',root:{selector:'#transferVthLabPage .dkds-plugin-workspace'},primary:{id:'vth-main',role:'analysis-primary',presentationRole:'scientific-primary',priority:100,collapsible:false},prime:[{id:'data-control',label:'数据',semanticKind:'panel',presentationPurpose:'parameters',presentationRole:'data-control',priority:90,collapsible:true}],sub:[]}});

    const offArtifacts=ctx.events.on('data:artifacts-changed',()=>refreshSources({announce:false}));
    curves=loadAssignedCurves();if(curves.length){sourceMode='project';state.patch({selectedCurveId:curves[0].id});}else{sourceMode='empty';state.patch({selectedCurveId:null});}
    renderAll('initial');
    liveDomain=LiveDomain.create({
      snapshot:liveSnapshot,
      actions:{
        refresh:payload=>refreshSources({announce:payload?.announce!==false}),
        demo:()=>loadDemo(),
        setSelectedCurve:selectCurveLive,
        setParameter:setParameterLive,
        setParameters:setParametersLive,
        setManualWindow:payload=>{const value=payload?.value??payload?.window??payload;applyManualWindow(value);return clone(state.get().manualWindows?.[selected()?.id]||null);},
        resetManualWindow:()=>resetManualWindow(),
        setView:setViewLive,
        fitView:()=>plotSurface?.fitToData?.({source:'vth-live-domain'})??false,
        analyzeSelected:()=>awaitResult(selected()),
        analyzeAll:()=>analyzeAllLive()
      }
    });
    liveStateOff=state.subscribe((_value,meta={})=>liveDomain?.notify?.('state',meta));
    if(!ctx.runtime.isAuxiliaryWindow)ctx.modules.require('domain-adapter')?.provide?.(ctx,liveDomain);
    liveDomain.notify('ready',{curves:curves.length,sourceMode});
    return{liveDomain,deactivate(){offSettings?.();liveStateOff?.();offArtifacts?.();presentation?.dispose?.();presentation=null;plotSurface=tableSurface=workbench=null;settings?.dispose?.();}};
  });
})();
