'use strict';
const {VISUAL_PARITY,NATIVE_PLUGIN_BLUEPRINTS}=require('./unit-blueprints');
const {NATIVE_PLUGIN_GEOMETRY_BLUEPRINTS,PRIVATE_GEOMETRY_BRIDGES}=require('./geometry-blueprints');
const {NATIVE_PLUGIN_SERVICE_BLUEPRINTS}=require('./service-blueprints');
const {NATIVE_PLUGIN_PRESENTATION_BLUEPRINTS}=require('./presentation-blueprints');
const {NATIVE_PLUGIN_STATE_BLUEPRINTS}=require('./state-blueprints');
module.exports=Object.freeze({VISUAL_PARITY,NATIVE_PLUGIN_BLUEPRINTS,NATIVE_PLUGIN_GEOMETRY_BLUEPRINTS,PRIVATE_GEOMETRY_BRIDGES,NATIVE_PLUGIN_SERVICE_BLUEPRINTS,NATIVE_PLUGIN_PRESENTATION_BLUEPRINTS,NATIVE_PLUGIN_STATE_BLUEPRINTS});
