(() => {
  const requiresCore=['runtime','status','io','services','workspace','ui.dom','ui.activities','ui.pages','ui.styles','ui.menus'];
  DKDSPlugins.define({
    id:'builtin.connectivity-center',pluginType:'foundation',name:'Connectivity & AI Center',version:'1.1.1',apiVersion:'1.16.0',requiresCore:requiresCore,
    order:34,description:'Provider files, SMB, full-kernel AI Agent and MCP connection center.',
    capabilities:['ui.activity','ui.page','files.provider-directory','network.smb','ai.agent.kernel','mcp.kernel-server']
  }, async ctx => {
    const dom=ctx.ui.dom;
    const connectivity=ctx.services.require('connectivity');
    const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const fmt=n=>{const v=Number(n)||0;if(v<1024)return `${v} B`;if(v<1048576)return `${(v/1024).toFixed(1)} KB`;return `${(v/1048576).toFixed(1)} MB`;};
    let tree=null,treePath='',treeEntries=[],selectedTree=null,smbPath='',smbEntries=[],selectedSmb=[];

    ctx.ui.styles.add('connectivity-center',`
      .dkcc{height:100%;display:flex;flex-direction:column;min-height:0;color:var(--dkui-text,#172033)}
      .dkcc-head{padding:18px 22px 10px;display:flex;align-items:flex-start;justify-content:space-between;gap:16px}
      .dkcc-head h2{margin:0;font-size:20px}.dkcc-sub{margin-top:5px;color:var(--dkui-text-muted,#718096);font-size:12px}
      .dkcc-tabs{display:flex;gap:6px;padding:0 22px 12px;flex-wrap:wrap}.dkcc-tab{border:1px solid var(--dkui-border);background:var(--dkui-surface-soft);color:inherit;border-radius:9px;padding:7px 12px;cursor:pointer}.dkcc-tab.active{border-color:color-mix(in srgb,var(--dkui-accent,#1677ff) 55%,transparent);background:color-mix(in srgb,var(--dkui-accent,#1677ff) 10%,var(--dkui-surface));color:var(--dkui-accent,#1677ff)}
      .dkcc-body{min-height:0;overflow:auto;padding:0 22px 24px}.dkcc-panel{display:none}.dkcc-panel.active{display:block}.dkcc-grid{display:grid;grid-template-columns:minmax(260px,360px) minmax(340px,1fr);gap:14px}.dkcc-card{background:var(--dkui-surface);border:1px solid var(--dkui-border);border-radius:13px;padding:14px;box-shadow:0 7px 20px rgba(15,23,42,.035)}
      .dkcc-card h3{font-size:14px;margin:0 0 10px}.dkcc-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.dkcc-field{display:grid;gap:5px;margin:8px 0}.dkcc-field label{font-size:11px;color:var(--dkui-text-muted)}.dkcc input,.dkcc select,.dkcc textarea{box-sizing:border-box;width:100%;border:1px solid var(--dkui-border-strong);background:var(--dkui-control-bg,var(--dkui-surface));color:inherit;border-radius:9px;padding:8px 10px;outline:none}.dkcc textarea{min-height:96px;resize:vertical}.dkcc button{border:1px solid var(--dkui-border-strong);background:var(--dkui-surface);color:inherit;border-radius:9px;padding:7px 11px;cursor:pointer}.dkcc button.primary{background:var(--dkui-accent,#1677ff);border-color:transparent;color:#fff}.dkcc button:disabled{opacity:.45;cursor:default}
      .dkcc-list{margin-top:10px;display:grid;gap:4px;max-height:420px;overflow:auto}.dkcc-item{display:grid;grid-template-columns:24px minmax(0,1fr) auto;gap:8px;align-items:center;border-radius:8px;padding:7px 8px;cursor:pointer}.dkcc-item:hover{background:var(--dkui-surface-hover)}.dkcc-item.selected{background:color-mix(in srgb,var(--dkui-accent,#1677ff) 10%,transparent)}.dkcc-name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dkcc-meta{font-size:10px;color:var(--dkui-text-muted)}.dkcc-note{font-size:11px;line-height:1.55;color:var(--dkui-text-muted);margin:8px 0}.dkcc-result{margin-top:10px;border-radius:9px;padding:10px;background:var(--dkui-surface-soft);font:11px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;word-break:break-word;max-height:260px;overflow:auto}.dkcc-status{font-size:12px;color:var(--dkui-text-muted)}.dkcc-checks{display:flex;gap:12px;flex-wrap:wrap;margin:9px 0}.dkcc-checks label{font-size:11px;display:flex;gap:5px;align-items:center}.dkcc-checks input{width:auto}.dkcc-danger{color:#d74b4b}
      @media(max-width:820px){.dkcc-head{padding:12px 14px 8px}.dkcc-tabs{padding:0 14px 9px}.dkcc-body{padding:0 14px 18px}.dkcc-grid{grid-template-columns:1fr}.dkcc-card{padding:12px}.dkcc-list{max-height:300px}}
      [data-dkds-theme="dark"] .dkcc-card{box-shadow:none}
    `);

    const page=ctx.ui.pages.add({
      id:'connectivity-center',pageId:'connectivityCenterPage',activity:'connectivity-center',label:'连接与 AI',title:'连接与 AI',order:34,toolbar:false,
      html:`<div class="dkcc">
        <div class="dkcc-head"><div><h2>连接与 AI</h2><div class="dkcc-sub">文件 Provider、SMB、AI Agent 与 MCP 使用同一套 Core 契约；移动端系统能力由 Native Host 提供。</div></div></div>
        <div class="dkcc-tabs"><button class="dkcc-tab active" data-tab="files">文件</button><button class="dkcc-tab" data-tab="smb">SMB</button><button class="dkcc-tab" data-tab="agent">AI Agent</button><button class="dkcc-tab" data-tab="mcp">MCP</button></div>
        <div class="dkcc-body">
          <section class="dkcc-panel active" data-panel="files"><div class="dkcc-grid"><div class="dkcc-card"><h3>系统文件 Provider</h3><div class="dkcc-note">Android 使用 Storage Access Framework，可进入支持 DocumentsProvider 的第三方文件管理器、云盘或网络存储；桌面端使用原生文件夹。</div><div class="dkcc-row"><button id="dkccChooseFolder" class="primary">选择文件夹</button><button id="dkccFolderUp">上一级</button><button id="dkccFolderRefresh">刷新</button></div><div id="dkccFolderPath" class="dkcc-note">尚未选择文件夹</div><div id="dkccFolderList" class="dkcc-list"></div></div><div class="dkcc-card"><h3>读取接口</h3><div id="dkccFileSelection" class="dkcc-note">选择左侧文件后可直接通过 Host 读取，不要求复制进 Studio 私有目录。</div><div class="dkcc-row"><button id="dkccReadFile" class="primary" disabled>读取选中文件</button></div><pre id="dkccFileResult" class="dkcc-result">—</pre></div></div></section>
          <section class="dkcc-panel" data-panel="smb"><div class="dkcc-grid"><div class="dkcc-card"><h3>SMB 连接</h3><div class="dkcc-field"><label>服务器</label><input id="dkccSmbServer" placeholder="192.168.1.10 或 NAS 名称"></div><div class="dkcc-field"><label>共享名</label><input id="dkccSmbShare" placeholder="Data"></div><div class="dkcc-row"><div class="dkcc-field" style="flex:1"><label>用户名</label><input id="dkccSmbUser"></div><div class="dkcc-field" style="flex:1"><label>域</label><input id="dkccSmbDomain"></div></div><div class="dkcc-field"><label>密码</label><input id="dkccSmbPassword" type="password"></div><div class="dkcc-row"><button id="dkccSmbDiscover">发现服务器</button><button id="dkccSmbShares">枚举共享</button><button id="dkccSmbOpen" class="primary">打开共享</button></div><div id="dkccSmbDiscovery" class="dkcc-list"></div></div><div class="dkcc-card"><h3>共享文件</h3><div class="dkcc-row"><button id="dkccSmbUp">上一级</button><button id="dkccSmbRefresh">刷新</button><button id="dkccSmbRead" class="primary" disabled>读取选中</button></div><div id="dkccSmbPath" class="dkcc-note">/</div><div id="dkccSmbList" class="dkcc-list"></div><pre id="dkccSmbResult" class="dkcc-result">—</pre></div></div></section>
          <section class="dkcc-panel" data-panel="agent"><div class="dkcc-grid"><div class="dkcc-card"><h3>AI Provider</h3><div class="dkcc-field"><label>预设</label><select id="dkccAgentPreset"></select></div><div class="dkcc-field"><label>Endpoint</label><input id="dkccAgentEndpoint"></div><div class="dkcc-field"><label>模型</label><input id="dkccAgentModel"></div><div class="dkcc-field"><label>API Key</label><input id="dkccAgentKey" type="password" placeholder="保存在系统安全存储，不进入项目文件"></div><div class="dkcc-field"><label>内核权限</label><select id="dkccAgentAccess"><option value="full">完整内核（推荐）</option><option value="read-only">只读分析</option></select></div><div class="dkcc-field"><label>最大工具轮次</label><input id="dkccAgentRounds" type="number" min="1" max="24" value="12"></div><div class="dkcc-row"><button id="dkccAgentSave">保存设置</button><button id="dkccAgentTest">测试连接</button></div><div class="dkcc-note">完整内核模式可读取/清洗数据、分析当前数据图、绘图、运行科学变换与 Workflow、访问 Core/插件 Capability、管理项目历史，并可校验/安装 AI 生成的 .dkplugin。API Key 仅保存在宿主安全存储中。</div></div><div class="dkcc-card"><h3>内核 Agent</h3><div class="dkcc-field"><label>任务</label><textarea id="dkccAgentPrompt" placeholder="例如：分析当前工程全部 I–V 数据，清洗异常点，绘制导数对比图，并把可复用流程封装成插件。"></textarea></div><div class="dkcc-row"><button id="dkccAgentRun" class="primary">运行 Agent</button></div><pre id="dkccAgentResult" class="dkcc-result">Agent 尚未运行。</pre></div></div></section>
          <section class="dkcc-panel" data-panel="mcp"><div class="dkcc-grid"><div class="dkcc-card"><h3>MCP Server</h3><div class="dkcc-note">Streamable HTTP：<code>POST /mcp</code>。语义由 Studio Core 统一处理，桌面与 Android 仅负责网络传输。</div><div class="dkcc-field"><label>访问 Token</label><input id="dkccMcpToken" placeholder="至少 12 个字符"></div><div class="dkcc-row"><button id="dkccMcpStart" class="primary">启动</button><button id="dkccMcpStop">停止</button><button id="dkccMcpRefresh">刷新</button></div></div><div class="dkcc-card"><h3>服务状态</h3><div id="dkccMcpStatus" class="dkcc-status">检查中…</div><pre id="dkccMcpInfo" class="dkcc-result">—</pre></div></div></section>
        </div></div>`
    });
    ctx.ui.activities.add({id:'connectivity-center',label:'连接与 AI',contextLabel:'连接与 AI',icon:'◎',order:34,navigation:'system',primary:false,description:'SMB、文件 Provider、AI Agent 与 MCP',onActivate:()=>ctx.workspace.openPage('connectivityCenterPage')});
    // Pages that belong to an Activity also carry Core's plugin-activity-hidden state.
    // A tools-menu shortcut must activate that Activity first; directly calling
    // workspace.openPage() only clears the page's ordinary `hidden` class and
    // therefore leaves the page invisible while another Activity is active.
    if(!ctx.runtime.isAuxiliaryWindow&&ctx.ui.menus?.add)ctx.ui.menus.add({id:'connectivity-center',menu:'tools',label:'连接 / SMB / AI / MCP',order:34,onClick:()=>ctx.ui.activities.activate('connectivity-center')});

    const $=sel=>dom.query(sel,page),$$=sel=>[...(page.querySelectorAll?.(sel)||[])];
    const setText=(sel,value)=>{const el=$(sel);if(el)el.textContent=String(value??'');};
    const busy=async(button,fn)=>{const el=$(button);if(el)el.disabled=true;try{return await fn();}finally{if(el)el.disabled=false;}};
    const switchTab=id=>{$$('.dkcc-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.dkcc-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===id));};
    $$('.dkcc-tab').forEach(el=>dom.on(el,'click',()=>switchTab(el.dataset.tab)));

    function renderTree(){
      setText('#dkccFolderPath',tree?`${tree.name||'Provider'} · /${treePath}`:'尚未选择文件夹');
      const host=$('#dkccFolderList');if(!host)return;
      host.innerHTML=treeEntries.length?treeEntries.map((row,i)=>`<div class="dkcc-item ${selectedTree===i?'selected':''}" data-tree-index="${i}"><span>${row.directory?'▸':'·'}</span><span class="dkcc-name">${esc(row.name)}</span><span class="dkcc-meta">${row.directory?'文件夹':fmt(row.size)}</span></div>`).join(''):'<div class="dkcc-note">当前目录没有可读取的数据文件。</div>';
      const read=$('#dkccReadFile');if(read)read.disabled=selectedTree==null||!!treeEntries[selectedTree]?.directory;
    }
    async function refreshTree(){if(!tree)return;const response=await connectivity.files.listDirectory({uri:tree.uri,root:tree.path||tree.root,relativePath:treePath});treeEntries=Array.isArray(response)?response:(response?.entries||[]);selectedTree=null;renderTree();}
    dom.on($('#dkccChooseFolder'),'click',()=>busy('#dkccChooseFolder',async()=>{const row=await connectivity.files.openDirectory();if(!row)return;tree=row;treePath='';await refreshTree();}));
    dom.on($('#dkccFolderRefresh'),'click',()=>busy('#dkccFolderRefresh',refreshTree));
    dom.on($('#dkccFolderUp'),'click',()=>{if(!treePath)return;treePath=treePath.split('/').slice(0,-1).join('/');void refreshTree();});
    dom.on($('#dkccFolderList'),'click',event=>{const row=event.target?.closest?.('[data-tree-index]');if(!row)return;const i=Number(row.dataset.treeIndex),entry=treeEntries[i];if(!entry)return;if(entry.directory){treePath=entry.relativePath||entry.path||[treePath,entry.name].filter(Boolean).join('/');void refreshTree();return;}selectedTree=i;setText('#dkccFileSelection',`${entry.name} · ${fmt(entry.size)}`);renderTree();});
    dom.on($('#dkccReadFile'),'click',()=>busy('#dkccReadFile',async()=>{const entry=treeEntries[selectedTree];if(!entry)return;const result=await connectivity.files.read({uri:entry.uri,path:entry.path,name:entry.name});const size=result?.size||entry.size||(result?.base64?Math.floor(result.base64.length*3/4):new TextEncoder().encode(result?.text||'').length);setText('#dkccFileResult',JSON.stringify({name:entry.name,size,encoding:result?.text?'text':'base64',read:true},null,2));ctx.status.set(`已通过系统 Provider 读取 ${entry.name}（${fmt(size)}）。`);}));

    const smbConnection=()=>({server:$('#dkccSmbServer')?.value||'',share:$('#dkccSmbShare')?.value||'',username:$('#dkccSmbUser')?.value||'',password:$('#dkccSmbPassword')?.value||'',domain:$('#dkccSmbDomain')?.value||''});
    function renderSmb(){setText('#dkccSmbPath','/'+smbPath);const host=$('#dkccSmbList');if(host)host.innerHTML=smbEntries.length?smbEntries.map((row,i)=>`<div class="dkcc-item ${selectedSmb.includes(i)?'selected':''}" data-smb-index="${i}"><span>${row.directory?'▸':'·'}</span><span class="dkcc-name">${esc(row.name)}</span><span class="dkcc-meta">${row.directory?'文件夹':fmt(row.size)}</span></div>`).join(''):'<div class="dkcc-note">当前共享没有可显示文件。</div>';const button=$('#dkccSmbRead');if(button)button.disabled=!selectedSmb.length;}
    async function refreshSmb(){smbEntries=await connectivity.smb.list(smbConnection(),smbPath)||[];selectedSmb=[];renderSmb();}
    dom.on($('#dkccSmbDiscover'),'click',()=>busy('#dkccSmbDiscover',async()=>{const rows=await connectivity.smb.discover()||[];const host=$('#dkccSmbDiscovery');if(host)host.innerHTML=rows.length?rows.map((row,i)=>`<div class="dkcc-item" data-server="${esc(row.address)}"><span>●</span><span class="dkcc-name">${esc(row.name||row.address)}</span><span class="dkcc-meta">${esc(row.address)}</span></div>`).join(''):'<div class="dkcc-note">没有发现开放 445 端口的 SMB 主机。</div>';}));
    dom.on($('#dkccSmbDiscovery'),'click',event=>{const row=event.target?.closest?.('[data-server]');if(row&&$('#dkccSmbServer'))$('#dkccSmbServer').value=row.dataset.server||'';});
    dom.on($('#dkccSmbShares'),'click',()=>busy('#dkccSmbShares',async()=>{const rows=await connectivity.smb.listShares(smbConnection())||[];const host=$('#dkccSmbDiscovery');if(host)host.innerHTML=rows.map(name=>`<div class="dkcc-item" data-share="${esc(name)}"><span>▣</span><span class="dkcc-name">${esc(name)}</span><span></span></div>`).join('')||'<div class="dkcc-note">服务器未返回可枚举共享；可手动输入共享名。</div>';}));
    dom.on($('#dkccSmbDiscovery'),'click',event=>{const row=event.target?.closest?.('[data-share]');if(row&&$('#dkccSmbShare'))$('#dkccSmbShare').value=row.dataset.share||'';});
    dom.on($('#dkccSmbOpen'),'click',()=>busy('#dkccSmbOpen',async()=>{smbPath='';await refreshSmb();}));dom.on($('#dkccSmbRefresh'),'click',()=>busy('#dkccSmbRefresh',refreshSmb));dom.on($('#dkccSmbUp'),'click',()=>{if(!smbPath)return;smbPath=smbPath.split('/').slice(0,-1).join('/');void refreshSmb();});
    dom.on($('#dkccSmbList'),'click',event=>{const row=event.target?.closest?.('[data-smb-index]');if(!row)return;const i=Number(row.dataset.smbIndex),entry=smbEntries[i];if(!entry)return;if(entry.directory){smbPath=entry.path||[smbPath,entry.name].filter(Boolean).join('/');void refreshSmb();return;}selectedSmb=selectedSmb.includes(i)?selectedSmb.filter(x=>x!==i):[...selectedSmb,i];renderSmb();});
    dom.on($('#dkccSmbRead'),'click',()=>busy('#dkccSmbRead',async()=>{const paths=selectedSmb.map(i=>smbEntries[i]?.path).filter(Boolean);const files=await connectivity.smb.read(smbConnection(),paths);setText('#dkccSmbResult',JSON.stringify((files||[]).map(file=>({name:file.name||file.path,size:file.size||Math.floor((file.base64?.length||0)*3/4),read:true})),null,2));ctx.status.set(`已从 SMB 读取 ${files?.length||0} 个文件。`);}));

    const presets=connectivity.agent.presets();const preset=$('#dkccAgentPreset');if(preset)preset.innerHTML=presets.map(row=>`<option value="${esc(row.id)}">${esc(row.label)}</option>`).join('');
    function agentSettings(){return {presetId:$('#dkccAgentPreset')?.value||'custom',provider:presets.find(x=>x.id===$('#dkccAgentPreset')?.value)?.provider||'openai-compatible',endpoint:$('#dkccAgentEndpoint')?.value||'',model:$('#dkccAgentModel')?.value||'',accessMode:$('#dkccAgentAccess')?.value||'full',maxToolRounds:Number($('#dkccAgentRounds')?.value)||12};}
    function applyAgentSettings(settings){const row=presets.find(x=>x.id===settings.presetId)||presets[0];if(preset)preset.value=settings.presetId||row.id;if($('#dkccAgentEndpoint'))$('#dkccAgentEndpoint').value=settings.endpoint||row.endpoint||'';if($('#dkccAgentModel'))$('#dkccAgentModel').value=settings.model||row.models?.[0]||'';if($('#dkccAgentAccess'))$('#dkccAgentAccess').value=settings.accessMode==='read-only'?'read-only':'full';if($('#dkccAgentRounds'))$('#dkccAgentRounds').value=String(settings.maxToolRounds||12);}
    applyAgentSettings(connectivity.agent.loadSettings());
    dom.on(preset,'change',()=>{const row=presets.find(x=>x.id===preset.value);if(!row)return;if($('#dkccAgentEndpoint'))$('#dkccAgentEndpoint').value=row.endpoint||'';if($('#dkccAgentModel'))$('#dkccAgentModel').value=row.models?.[0]||'';});
    dom.on($('#dkccAgentSave'),'click',()=>busy('#dkccAgentSave',async()=>{const settings=connectivity.agent.saveSettings(agentSettings()),key=$('#dkccAgentKey')?.value||'';if(key)await connectivity.agent.setSecret(settings.presetId,key);ctx.status.set('AI Agent 设置已保存。');}));
    dom.on($('#dkccAgentTest'),'click',()=>busy('#dkccAgentTest',async()=>{const settings=connectivity.agent.saveSettings(agentSettings()),key=$('#dkccAgentKey')?.value||'';if(key)await connectivity.agent.setSecret(settings.presetId,key);await connectivity.agent.test(settings);ctx.status.set('AI Provider 连接测试通过。');}));
    dom.on($('#dkccAgentRun'),'click',()=>busy('#dkccAgentRun',async()=>{const settings=connectivity.agent.saveSettings(agentSettings()),key=$('#dkccAgentKey')?.value||'';if(key)await connectivity.agent.setSecret(settings.presetId,key);setText('#dkccAgentResult','Agent 正在读取 Studio 内核并执行任务…');const result=await connectivity.agent.run($('#dkccAgentPrompt')?.value||'',settings);setText('#dkccAgentResult',`${result.text||'任务完成。'}

工具调用：${result.audit?.length||0} · 轮次：${result.rounds||0} · Run ID：${result.runId||''}`);ctx.status.set(`AI Agent 已完成任务 · ${result.audit?.length||0} 次内核调用。`);}));

    async function refreshMcp(){const state=await connectivity.mcp.status();setText('#dkccMcpStatus',state?.running?'运行中':'未启动');setText('#dkccMcpInfo',JSON.stringify({running:!!state?.running,url:state?.url||'',tokenHeader:state?.tokenHeader||'x-dkds-token',protocol:['2025-06-18','2025-11-25'],error:state?.error||''},null,2));}
    dom.on($('#dkccMcpRefresh'),'click',()=>busy('#dkccMcpRefresh',refreshMcp));dom.on($('#dkccMcpStart'),'click',()=>busy('#dkccMcpStart',async()=>{let token=$('#dkccMcpToken')?.value||'';if(token.length<12){token=`dkds-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;$('#dkccMcpToken').value=token;}await connectivity.mcp.start(token);await refreshMcp();ctx.status.set('MCP Server 已启动。');}));dom.on($('#dkccMcpStop'),'click',()=>busy('#dkccMcpStop',async()=>{await connectivity.mcp.stop();await refreshMcp();}));
    void refreshMcp().catch(()=>setText('#dkccMcpStatus','状态不可用'));
    return {deactivate(){}};
  });
})();
