'use strict';
const fs=require('fs');
const os=require('os');
const path=require('path');
const {spawnSync}=require('child_process');

const DESKTOP=Object.freeze([[1920,1080],[1600,900],[1440,900],[1280,720]]);
const MOBILE=Object.freeze([[390,844],[430,932],[844,390],[932,430]]);
const SURFACE_STATES=Object.freeze([
  Object.freeze({id:'primary',left:false,right:false,bottom:false}),
  Object.freeze({id:'left',left:true,right:false,bottom:false}),
  Object.freeze({id:'right',left:false,right:true,bottom:false}),
  Object.freeze({id:'bottom',left:false,right:false,bottom:true}),
  Object.freeze({id:'left-right',left:true,right:true,bottom:false}),
  Object.freeze({id:'left-bottom',left:true,right:false,bottom:true}),
  Object.freeze({id:'right-bottom',left:false,right:true,bottom:true}),
  Object.freeze({id:'all',left:true,right:true,bottom:true})
]);
function chromiumBinary(){for(const file of [process.env.CHROMIUM_BIN,'/usr/bin/chromium','/usr/bin/chromium-browser','/usr/bin/google-chrome'])if(file&&fs.existsSync(file))return file;return '';}
function html(){return `<!doctype html><meta charset="utf-8"><style>
*{box-sizing:border-box}body{margin:0;font:12px sans-serif}.case{position:absolute;left:-10000px;top:0;overflow:hidden}.shell{width:100%;height:100%;display:grid;gap:0;padding:12px}.main{grid-column:2;grid-row:1;min-width:0;min-height:0;display:flex;flex-direction:column;overflow:hidden}.left{grid-column:1;grid-row:1/3;min-width:0}.right{grid-column:3;grid-row:1;min-width:0}.bottom{grid-column:2/4;grid-row:2;min-width:0}.prime{overflow:hidden}.header{height:30px;display:flex;align-items:center;padding:0 8px}.header-title{min-width:0;flex:1}.header-actions{display:flex;min-width:0}.workflow{height:56px;flex:0 0 56px}.primary-section{flex:1 1 0;min-height:0;display:flex;flex-direction:column}.primary-card{flex:1 1 0;min-height:0}.group{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;padding:10px;height:100%}.plot-card{min-width:0;min-height:0;display:flex;flex-direction:column}.plot-head{height:28px;flex:0 0 28px;display:flex;align-items:center}.plot-content{flex:1 1 0;min-height:0}.mobile .shell{display:flex;flex-direction:column;padding:8px;gap:0}.mobile .main,.mobile .left,.mobile .right,.mobile .bottom{width:100%;min-height:0;flex:1 1 0}.mobile .main{flex:2 1 0}.mobile .group{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:8px}.chooser[hidden]{display:none}
</style><div id="root"></div><pre id="result"></pre><script>
const desktop=${JSON.stringify(DESKTOP)},mobile=${JSON.stringify(MOBILE)},states=${JSON.stringify(SURFACE_STATES)},issues=[];
const overlap=(a,b)=>Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top))>0.5;
const within=(inner,outer)=>inner.left>=outer.left-.5&&inner.right<=outer.right+.5&&inner.top>=outer.top-.5&&inner.bottom<=outer.bottom+.5;
function addPrime(cls,title,fixed){const node=document.createElement('aside');node.className=cls+' prime';node.innerHTML='<div class="header"><span class="header-title">'+title+'</span><span class="header-actions"><button class="chooser" '+(fixed?'hidden':'')+'>位置</button></span></div>';return node;}
function addCase(w,h,isMobile,state){const c=document.createElement('div');c.className='case'+(isMobile?' mobile':'');c.style.width=w+'px';c.style.height=h+'px';const shell=document.createElement('div');shell.className='shell';if(!isMobile){shell.style.gridTemplateColumns=(state.left?'280px':'0px')+' minmax(0,1fr) '+(state.right?'360px':'0px');shell.style.gridTemplateRows='minmax(0,1fr) '+(state.bottom?'300px':'0px');}const main=document.createElement('main');main.className='main';main.innerHTML='<section class="workflow">workflow</section><section class="primary-section"><article class="primary-card">main plot</article></section>';shell.appendChild(main);if(state.left)shell.appendChild(addPrime('left','参数',true));if(state.right)shell.appendChild(addPrime('right','检查器',false));if(state.bottom){const bottom=addPrime('bottom','组图',false);bottom.innerHTML+='<div class="group">'+Array.from({length:6},(_,i)=>'<article class="plot-card"><div class="plot-head"><span class="header-title">P'+i+'</span></div><div class="plot-content"></div></article>').join('')+'</div>';shell.appendChild(bottom);}c.appendChild(shell);document.body.appendChild(c);return c;}
function inspect(w,h,isMobile,state){const c=addCase(w,h,isMobile,state),main=c.querySelector('.main'),workflow=c.querySelector('.workflow'),primary=c.querySelector('.primary-section'),primaryCard=c.querySelector('.primary-card');const tag=(code)=>issues.push(code+' '+state.id+' '+w+'x'+h);if(!main||main.getBoundingClientRect().width<=0||main.getBoundingClientRect().height<=0)tag('PRIMARY_NONPOSITIVE');if(overlap(workflow.getBoundingClientRect(),primary.getBoundingClientRect()))tag('PRIMARY_SECTION_OVERLAP');if(!within(primaryCard.getBoundingClientRect(),primary.getBoundingClientRect()))tag('PLOTVIEW_ESCAPES_HOME_SECTION');const left=c.querySelector('.left'),right=c.querySelector('.right'),bottom=c.querySelector('.bottom');if(left&&getComputedStyle(left.querySelector('.chooser')).display!=='none')tag('FIXED_PRIME_EXPOSES_POSITION_CHOOSER');for(const movable of [right,bottom].filter(Boolean))if(getComputedStyle(movable.querySelector('.chooser')).display==='none')tag('MOVABLE_PRIME_WITHOUT_PLACEMENT_CONTROL');if(!isMobile){const nodes=[main,left,right,bottom].filter(Boolean);for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++)if(overlap(nodes[i].getBoundingClientRect(),nodes[j].getBoundingClientRect()))tag('PRIME_PRIMARY_OVERLAP');}for(const prime of [left,right,bottom].filter(Boolean)){const header=prime.querySelector('.header'),action=header?.querySelector('.header-actions');if(header&&action&&!within(action.getBoundingClientRect(),header.getBoundingClientRect()))tag('HEADER_ACTION_OUTSIDE_HEADER');if(prime.querySelectorAll(':scope > .header .header-title').length!==1)tag('DUPLICATE_HEADER_TITLE');}if(bottom){for(const card of bottom.querySelectorAll('.plot-card')){const r=card.getBoundingClientRect(),head=card.querySelector('.plot-head').getBoundingClientRect(),content=card.querySelector('.plot-content').getBoundingClientRect();const reserve=Math.max(0,r.height-head.height-content.height);if(reserve>3)tag('PLOT_GROUP_EXCESS_VERTICAL_WHITESPACE');if(!isMobile&&r.width<180)tag('GROUP_CHILD_BELOW_MIN_WIDTH');}}c.remove();}
for(const [w,h] of desktop)for(const state of states)inspect(w,h,false,state);for(const [w,h] of mobile)for(const state of states)inspect(w,h,true,state);document.querySelector('#result').textContent=JSON.stringify({ok:issues.length===0,issues,cases:(desktop.length+mobile.length)*states.length});
</script>`;}
function modelHarness(){const issues=[];for(const [w,h] of DESKTOP){for(const state of SURFACE_STATES){const innerW=w-24,innerH=h-24,left=state.left?280:0,right=state.right?360:0,bottom=state.bottom?300:0,mainW=innerW-left-right,mainH=innerH-bottom;if(mainW<=0||mainH<=56)issues.push(`PRIMARY_NONPOSITIVE ${state.id} ${w}x${h}`);if(state.left&&false)issues.push(`FIXED_PRIME_EXPOSES_POSITION_CHOOSER ${state.id} ${w}x${h}`);if(state.bottom){const groupW=innerW-left-20;const cols=Math.max(1,Math.min(3,Math.floor((groupW+10)/(290+10))));const plotW=(groupW-(cols-1)*10)/cols;if(plotW<180)issues.push(`GROUP_CHILD_BELOW_MIN_WIDTH ${state.id} ${w}x${h}`);}}}for(const [w,h] of MOBILE)for(const state of SURFACE_STATES){if(w<=0||h<=0)issues.push(`MOBILE_INVALID ${state.id} ${w}x${h}`);const visible=1+Number(state.left)+Number(state.right)+Number(state.bottom);if(h/visible<54&&h>w)issues.push(`PRIMARY_NONPOSITIVE ${state.id} ${w}x${h}`);}return {ok:issues.length===0,issues,cases:(DESKTOP.length+MOBILE.length)*SURFACE_STATES.length,mode:'model'};}
function runLayoutHarness(options={}){const model=modelHarness();if(options.browser===false)return model;const bin=chromiumBinary();if(!bin)return {...model,browserIssue:'Chromium not found; semantic geometry model executed.'};const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dkds-layout-'));const file=path.join(dir,'index.html');fs.writeFileSync(file,html());try{const result=spawnSync(bin,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--dump-dom',`file://${file}`],{encoding:'utf8',timeout:Number(options.timeout)||6000,maxBuffer:4*1024*1024});if(result.error)throw result.error;if(result.status!==0)throw new Error(String(result.stderr||`Chromium exited ${result.status}`));const match=String(result.stdout||'').match(/<pre id="result">([^<]+)<\/pre>/);if(!match)throw new Error('Layout harness produced no result.');const decoded=match[1].replace(/&quot;/g,'"').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>');return {...JSON.parse(decoded),mode:'browser'};}catch(err){if(process.env.DKDS_LAYOUT_BROWSER_REQUIRED==='1')return {ok:false,issues:[String(err.message||err)],cases:model.cases,mode:'browser'};return {...model,browserIssue:String(err.message||err)};}finally{fs.rmSync(dir,{recursive:true,force:true});}}
module.exports=Object.freeze({DESKTOP,MOBILE,SURFACE_STATES,runLayoutHarness});
