(() => {
  const modules=window.DKDSPluginModules;if(!modules?.define)throw new Error('Plugin Module Runtime unavailable.');
  if(modules.get?.('builtin.standard-transport-algorithms','algorithm'))return;
  const VERSION='1.0.0';
  const finite=v=>Number.isFinite(Number(v));
  const median=values=>{const a=(values||[]).filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!a.length)return NaN;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;};
  const nearestIndex=(xs,target)=>{let best=-1,dist=Infinity;for(let i=0;i<(xs||[]).length;i++){const d=Math.abs(Number(xs[i])-Number(target));if(Number.isFinite(d)&&d<dist){dist=d;best=i;}}return best;};
  function movingAverage(y,radius){const out=new Array(y.length),r=Math.max(1,Math.round(radius));let sum=0;for(let i=0;i<y.length;i++){sum+=y[i];if(i-r-1>=0)sum-=y[i-r-1];const lo=Math.max(0,i-r),hi=i;out[i]=sum/(hi-lo+1);}const out2=new Array(y.length);sum=0;for(let i=y.length-1;i>=0;i--){sum+=out[i];if(i+r+1<y.length)sum-=out[i+r+1];const hi=Math.min(y.length-1,i+r),lo=i;out2[i]=sum/(hi-lo+1);}return out2;}
  function derivativeArray(y,x){const out=new Array(y.length).fill(NaN);if(y.length<2)return out;for(let j=1;j<y.length-1;j++){const dx=x[j+1]-x[j-1];if(Number.isFinite(y[j-1])&&Number.isFinite(y[j+1])&&Math.abs(dx)>1e-15)out[j]=(y[j+1]-y[j-1])/dx;}if(y.length>=2){const dx0=x[1]-x[0],dx1=x.at(-1)-x.at(-2);if(Number.isFinite(y[0])&&Number.isFinite(y[1])&&Math.abs(dx0)>1e-15)out[0]=(y[1]-y[0])/dx0;if(Number.isFinite(y.at(-1))&&Number.isFinite(y.at(-2))&&Math.abs(dx1)>1e-15)out[out.length-1]=(y.at(-1)-y.at(-2))/dx1;}return out;}
  function computeTransformSweep(sweep,type='raw',options={}){
    const pts=sweep?.points||[];if(!pts.length)return {type,points:[],unit:'',label:type};
    const x=pts.map(p=>p.v),rawI=pts.map(p=>p.i),absI=rawI.map(Math.abs);
    const step=Math.abs(sweep.step||median(x.slice(1).map((v,i)=>v-x[i]))||0.01),radius=Math.max(1,Math.round(options.radius??2));
    const smI=movingAverage(rawI,radius),smAbs=movingAverage(absI,radius),bgRadius=Math.max(radius+3,Math.round(0.14/Math.max(step,1e-12))),bg=movingAverage(absI,bgRadius),residual=absI.map((v,i)=>v-bg[i]);
    const didv=derivativeArray(smI,x),d2idv2=derivativeArray(didv,x),dAbsDidv=derivativeArray(smAbs,x),d2abs=derivativeArray(dAbsDidv,x);
    const currentScale=Math.max(median(absI.filter(v=>v>0))||0,1e-30),currentFloor=Math.max(options.currentFloor||0,currentScale*1e-7,1e-18),logI=absI.map(v=>Math.log(Math.max(v,currentFloor))),dlog=derivativeArray(movingAverage(logI,radius),x);
    const gScale=Math.max(median(didv.filter(Number.isFinite).map(Math.abs))||0,1e-30),gFloor=Math.max(gScale*1e-3,1e-30),dvdi=didv.map(g=>Number.isFinite(g)&&Math.abs(g)>gFloor?1/g:NaN),resistance=pts.map(p=>Math.abs(p.i)>currentFloor?Math.abs(p.v/p.i):NaN);
    const defs={raw:{y:rawI,label:'原始 I–V',unit:'A'},detrend:{y:residual,label:'去背景 I−I_bg',unit:'A'},didv:{y:didv,label:'dI/dV',unit:'A/V'},d2idv2:{y:d2idv2,label:'d²I/dV²',unit:'A/V²'},dlog:{y:dlog,label:'d ln|I|/dV',unit:'1/V'},dvdi:{y:dvdi,label:'dV/dI',unit:'V/A'},resistance:{y:resistance,label:'R=|V/I|',unit:'Ω'}};
    const def=defs[type]||defs.raw;
    return {type,label:def.label,unit:def.unit,points:pts.map((p,i)=>({v:p.v,y:def.y[i],rawIndex:i,rawI:p.i})),background:bg,residual,didv,d2idv2,d2abs,dlog,dvdi,resistance};
  }
  const TRANSFORM_TYPES=new Set(['raw','detrend','didv','d2idv2','dlog','dvdi','resistance']);
  function computeSweepScalarField(sweeps,targets,vgs,options={},transformRunner=null){
    const type=TRANSFORM_TYPES.has(String(options.type||options.transformId||''))?String(options.type||options.transformId):'didv',direction=Number(options.direction)<0?-1:1;
    const requestedTargets=(targets||options.targets||[]).map(Number).filter(Number.isFinite),requestedVgs=(vgs||options.vgs||[]).map(Number).filter(Number.isFinite),optionTolerance=Number(options.tolerance),hasTolerance=Number.isFinite(optionTolerance)&&optionTolerance>=0,sourceFileByVg=options.sourceFileByVg&&typeof options.sourceFileByVg==='object'?options.sourceFileByVg:{},transformOptions=options.transformOptions&&typeof options.transformOptions==='object'?options.transformOptions:{};
    let label=type,unit='';const sources=[];
    const matrix=requestedVgs.map(vg=>{let candidates=(sweeps||[]).filter(sw=>Number(sw?.direction)===direction&&Number.isFinite(Number(sw?.vg))&&Math.abs(Number(sw.vg)-vg)<=Math.max(1e-10,Math.abs(vg)*1e-9));const preferred=String(sourceFileByVg[String(vg)]??sourceFileByVg[vg]??'');if(preferred){const exact=candidates.filter(sw=>String(sw?.datasetName||'')===preferred);if(exact.length)candidates=exact;}const sweep=candidates[0]||null;if(!sweep){sources.push('');return requestedTargets.map(()=>NaN);}sources.push(String(sweep.datasetName||''));const transformed=typeof transformRunner==='function'?transformRunner(sweep,type,transformOptions):computeTransformSweep(sweep,type,transformOptions);label=transformed?.label||label;unit=transformed?.unit||unit;const points=transformed?.points||[],xs=points.map(p=>Number(p.v)),tol=hasTolerance?optionTolerance:Math.max(1e-12,Math.abs(Number(sweep.step)||0)*0.05);return requestedTargets.map(target=>{if(!points.length)return NaN;const j=nearestIndex(xs,target),point=points[j];if(!point||!Number.isFinite(point.v)||Math.abs(point.v-target)>tol)return NaN;return Number.isFinite(Number(point.y))?Number(point.y):NaN;});});
    const missing=matrix.reduce((sum,row)=>sum+row.filter(v=>!Number.isFinite(v)).length,0);return {type,direction,label,unit,targets:requestedTargets,vgs:requestedVgs,matrix,sources,missing};
  }
  function detectTerVoltageParameters(datasets){let globalMin=Infinity,globalMax=-Infinity,globalStep=Infinity;for(const ds of datasets||[]){const pts=ds.points||[];for(const p of pts)if(Number.isFinite(p.v)){globalMin=Math.min(globalMin,p.v);globalMax=Math.max(globalMax,p.v);}for(let k=1;k<pts.length;k++){const d=Math.abs(pts[k].v-pts[k-1].v);if(Number.isFinite(d)&&d>1e-12)globalStep=Math.min(globalStep,d);}}if(!Number.isFinite(globalStep)||!Number.isFinite(globalMin)||!Number.isFinite(globalMax)||globalMax<=globalMin)throw new Error('无法从当前项目检测有效的 Vds 范围或步长。');return {vmin:globalMin,vmax:globalMax,vstep:globalStep};}
  function sweepDirectionsRaw(points,tolerance){const dirs=new Int8Array(points.length);for(let index=0;index<points.length;index++){if(index>0&&Math.abs(points[index].v-points[index-1].v)>tolerance)dirs[index]=points[index].v>points[index-1].v?1:-1;else if(index+1<points.length&&Math.abs(points[index+1].v-points[index].v)>tolerance)dirs[index]=points[index+1].v>points[index].v?1:-1;}return dirs;}
  function pythonRoundInt(value){const n=Number(value);if(!Number.isFinite(n))return NaN;const lo=Math.floor(n),frac=n-lo;if(frac===.5)return(Math.abs(lo)%2===0)?lo:lo+1;return Math.round(n);}
  function terVoltageGrid(vmin,vmax,step){if(!(vmin<0&&vmax>0))throw new Error('TER_max 要求 Vds 范围跨过 0 V。');if(!(step>0))throw new Error('Vds 步长必须大于 0。');const nNegative=pythonRoundInt(Math.abs(vmin)/step),nPositive=pythonRoundInt(vmax/step);if(!Number.isFinite(nNegative)||!Number.isFinite(nPositive)||nNegative<0||nPositive<0)throw new Error('无法生成有效的 TER Vds 网格。');const negative=[];for(let index=0;index<nNegative;index++)negative.push(Number((vmin+index*step).toFixed(12)));const positive=[];for(let index=0;index<nPositive;index++)positive.push(Number(((index+1)*step).toFixed(12)));return negative.concat(positive);}
  function calculateTerHighLow(rUp,rDown){if(!Number.isFinite(rUp)||!Number.isFinite(rDown))return NaN;const low=Math.min(rUp,rDown),high=Math.max(rUp,rDown);return low!==0?(high-low)/low*100:NaN;}
  function processDatasetTer(dataset,targets,tolerance,currentFloor){const pts=dataset.points||[],dirs=sweepDirectionsRaw(pts,tolerance),records=[];for(const target of targets){let upIndex=-1,downIndex=-1;for(let k=0;k<pts.length;k++){if(Math.abs(pts[k].v-target)<=tolerance){if(upIndex<0&&dirs[k]===1)upIndex=k;if(downIndex<0&&dirs[k]===-1)downIndex=k;if(upIndex>=0&&downIndex>=0)break;}}const iUp=upIndex>=0?pts[upIndex].i:NaN,iDown=downIndex>=0?pts[downIndex].i:NaN,rUp=Number.isFinite(iUp)&&Math.abs(iUp)>currentFloor?Math.abs(target/iUp):NaN,rDown=Number.isFinite(iDown)&&Math.abs(iDown)>currentFloor?Math.abs(target/iDown):NaN,ter=Number.isFinite(rUp)&&Number.isFinite(rDown)?calculateTerHighLow(rUp,rDown):NaN;records.push({vg:dataset.vg,vds:target,iUp,iDown,rUp,rDown,ter,sourceFile:dataset.name});}return records;}
  function computeTerMatrix(datasets,options={}){if(!datasets?.length)throw new Error('当前项目没有可用于 TER_max 的数据。');const detected=detectTerVoltageParameters(datasets),optionNumber=(key,predicate=Number.isFinite)=>{const raw=options?.[key];if(raw===null||raw===undefined||raw==='')return null;const value=Number(raw);return predicate(value)?value:null;},vmin=optionNumber('vmin')??detected.vmin,vmax=optionNumber('vmax')??detected.vmax,vstep=optionNumber('vstep',v=>Number.isFinite(v)&&v>0)??detected.vstep,tolerance=optionNumber('tolerance',v=>Number.isFinite(v)&&v>=0)??vstep/20,currentFloor=optionNumber('currentFloor',v=>Number.isFinite(v)&&v>0)??1e-15,targets=terVoltageGrid(vmin,vmax,vstep),records=[];for(const ds of datasets)records.push(...processDatasetTer(ds,targets,tolerance,currentFloor));records.sort((x,y)=>(x.vg-y.vg)||(x.vds-y.vds));const vgs=[...new Set(records.map(r=>r.vg).filter(Number.isFinite))].sort((x,y)=>x-y),matrix=vgs.map(vg=>targets.map(vds=>{const r=records.find(q=>q.vg===vg&&Math.abs(q.vds-vds)<=Math.max(1e-12,tolerance*0.01));return r?.ter??NaN;})),terMaxByVg=[];for(const vg of vgs){const rows=records.filter(r=>r.vg===vg&&Number.isFinite(r.ter));if(!rows.length)continue;let best=rows[0];for(const r of rows)if(r.ter>best.ter)best=r;terMaxByVg.push({vg,terMax:best.ter,vdsAtMax:best.vds,iUp:best.iUp,iDown:best.iDown,rUp:best.rUp,rDown:best.rDown,sourceFile:best.sourceFile});}const terMaxByVd=[];for(const vds of targets){const rows=records.filter(r=>Math.abs(r.vds-vds)<=Math.max(1e-12,tolerance*0.01)&&Number.isFinite(r.ter));if(!rows.length)continue;let best=rows[0];for(const r of rows)if(r.ter>best.ter)best=r;terMaxByVd.push({vds,terMax:best.ter,vgAtMax:best.vg,iUp:best.iUp,iDown:best.iDown,rUp:best.rUp,rDown:best.rDown,sourceFile:best.sourceFile});}const missing=matrix.reduce((s,row)=>s+row.filter(v=>!Number.isFinite(v)).length,0);return {detected,used:{vmin,vmax,vstep,tolerance,currentFloor},targets,vgs,records,matrix,terMax:terMaxByVg,terMaxByVg,terMaxByVd,missing};}
  modules.define('builtin.standard-transport-algorithms','algorithm',Object.freeze({VERSION,computeTransformSweep,computeSweepScalarField,computeTerMatrix,calculateTerHighLow}));
})();
