'use strict';
const StyleGate=require('ui/style-ownership-gate');
const STYLE_OWNER='core.scientific-curve-renderer';
const STYLE_SOURCE='src/core/ui/modules/scientific-curve/render.js';
function selectionStyle(selection,property,value,component='scientific-curve-render'){selection?.each?.(function(d,i,nodes){const next=typeof value==='function'?value.call(this,d,i,nodes):value;if(next===null||next===undefined||next==='')StyleGate.remove(this,property,{owner:STYLE_OWNER,component,kind:'runtime-inline',source:STYLE_SOURCE});else StyleGate.set(this,property,next,{owner:STYLE_OWNER,component,kind:'runtime-inline',source:STYLE_SOURCE});});return selection;}
function selectionPaint(selection,attribute,value,component='scientific-curve-paint'){selection?.each?.(function(d,i,nodes){const next=typeof value==='function'?value.call(this,d,i,nodes):value;if(next===null||next===undefined||next==='')StyleGate.removePaint(this,attribute,{owner:STYLE_OWNER,component,scope:'scientific-render',source:STYLE_SOURCE});else StyleGate.setPaint(this,attribute,next,{owner:STYLE_OWNER,component,scope:'scientific-render',source:STYLE_SOURCE});});return selection;}
const VISIBILITY_OWNER='core.scientific-curve-visibility';
function selectionPresentation(selection,attribute,value,component='scientific-marker-visibility'){selection?.each?.(function(d,i,nodes){const next=typeof value==='function'?value.call(this,d,i,nodes):value;if(next===null||next===undefined||next==='')StyleGate.removePresentation(this,attribute,{owner:VISIBILITY_OWNER,component,scope:'scientific-render',source:STYLE_SOURCE});else StyleGate.setPresentation(this,attribute,next,{owner:VISIBILITY_OWNER,component,scope:'scientific-render',source:STYLE_SOURCE});});return selection;}

function applyScientificCurveRender(ScientificCurveSurface){
  class ScientificCurveRenderMixin {
    render(reason='render'){
      const d3=this.d3(),node=this.target,container=this.container;if(!d3||!node||!container)return false;
      const geometry=this.prepareLayoutGeometry();if(!geometry)return false;const {width,height}=geometry;
      if(geometry.status==='waiting'){this.awaitingLayout=true;return false;}this.awaitingLayout=false;
      const allCurves=this.curves(),svg=d3.select(node);svg.on('.dkdssci',null).attr('viewBox',null).attr('preserveAspectRatio',null).attr('width',width).attr('height',height);selectionStyle(svg,'width',`${width}px`,'scientific-curve-svg');selectionStyle(svg,'height',`${height}px`,'scientific-curve-svg');svg.selectAll('*').remove();
      if(!allCurves.length){this.renderLegend({enabled:false,entries:[]},allCurves);this.spec.onEmpty?.({svg,width,height});if(!this.spec.onEmpty)svg.append('text').attr('x',width/2).attr('y',height/2).attr('text-anchor','middle').call(selectionPaint,'fill','#6b7280').text(this.spec.emptyText||'没有可显示的数据');return true;}
      const baseMargin=this.adaptiveMargin(width,height),legendMetrics=this.computeLegendLayout(width,height,allCurves,baseMargin),margin={...baseMargin};if(legendMetrics.reserve>0&&legendMetrics.placement!=='none'){if(legendMetrics.placement==='right')margin.right=Math.max(margin.right,legendMetrics.reserve+8);else if(legendMetrics.placement==='left')margin.left=Math.max(margin.left,legendMetrics.reserve+40);else if(legendMetrics.placement==='top')margin.top=Math.max(margin.top,legendMetrics.reserve+8);else margin.bottom=Math.max(margin.bottom,legendMetrics.reserve+42);}this.renderLegend(legendMetrics,allCurves);const curves=this.visibleCurves(allCurves),innerW=Math.max(24,width-margin.left-margin.right),innerH=Math.max(24,height-margin.top-margin.bottom);
      const normalized=new Map(curves.map(curve=>[String(curve.id),this.normalizedPoints(curve)]));
      const xs=[...normalized.values()].flatMap(rows=>rows.map(p=>p.x)),ys=[...normalized.values()].flatMap(rows=>rows.map(p=>p.y));if(!xs.length||!ys.length)return false;
      const fullX=d3.extent(xs),logY=this.displayYAxisType==='log',displayYs=logY?ys.map(value=>Math.abs(Number(value))).filter(value=>Number.isFinite(value)&&value>0):ys;let fullY=d3.extent(displayYs.length?displayYs:ys);
      if(logY){const lo=Math.max(Number.MIN_VALUE,Number(fullY[0])),hi=Math.max(lo*(1+1e-9),Number(fullY[1])),logLo=Math.log10(lo),logHi=Math.log10(hi),span=Math.max(1e-6,logHi-logLo),pad=Math.max(.08,span*Number(this.spec.yPaddingFactor??.07));fullY=[Math.pow(10,logLo-pad),Math.pow(10,logHi+pad)];}
      else{const ypad=((fullY[1]-fullY[0])||1)*Number(this.spec.yPaddingFactor??.06);fullY=[fullY[0]-ypad,fullY[1]+ypad];}
      const view=this.view();let xDomain=Array.isArray(view.xDomain)?view.xDomain.slice():d3.scaleLinear().domain(fullX).nice().domain(),candidateY=Array.isArray(view.yDomain)?view.yDomain.slice():null,yDomain=(candidateY&&(!logY||candidateY.every(value=>Number(value)>0)))?candidateY:(logY?fullY.slice():d3.scaleLinear().domain(fullY).nice().domain());
      if(!xDomain.every(Number.isFinite)||xDomain[0]===xDomain[1])xDomain=fullX.slice();if(!yDomain.every(Number.isFinite)||yDomain[0]===yDomain[1]||(logY&&yDomain.some(value=>Number(value)<=0)))yDomain=fullY.slice();
      const x=d3.scaleLinear().domain(xDomain).range([margin.left,margin.left+innerW]),y=(logY?d3.scaleLog():d3.scaleLinear()).domain(yDomain).range([margin.top+innerH,margin.top]);
      const clipId=`dkds-sci-clip-${Math.random().toString(36).slice(2,9)}`;svg.append('defs').append('clipPath').attr('id',clipId).append('rect').attr('x',margin.left).attr('y',margin.top).attr('width',innerW).attr('height',innerH);
      const plotBg=svg.append('rect').attr('class','dkds-scientific-plot-bg').attr('x',margin.left).attr('y',margin.top).attr('width',innerW).attr('height',innerH);selectionStyle(plotBg,'cursor','crosshair','scientific-plot-background');
      svg.append('g').attr('class','dkds-scientific-axis dkds-scientific-x-axis').attr('transform',`translate(0,${margin.top+innerH})`).call(d3.axisBottom(x).tickFormat(this.spec.xTickFormat||undefined));
      const yAxisGenerator=d3.axisLeft(y).tickFormat(this.spec.yTickFormat||undefined);if(logY)yAxisGenerator.tickValues(this.logDecadeTicks(y.domain()));
      const yAxis=svg.append('g').attr('class','dkds-scientific-axis dkds-scientific-y-axis').attr('transform',`translate(${margin.left},0)`).call(yAxisGenerator);selectionStyle(yAxis,'cursor','pointer','scientific-y-axis');
      const toggleY=event=>{event.preventDefault();event.stopPropagation();this.toggleYAxisDisplay({event,source:'axis-double-click'});};
      const yAxisHit=svg.append('rect').attr('class','dkds-scientific-y-axis-hit').attr('x',0).attr('y',Math.max(0,margin.top-14)).attr('width',margin.left+12).attr('height',innerH+28).call(selectionPaint,'fill','transparent').on('dblclick.dkdsyaxis',toggleY);selectionStyle(yAxisHit,'cursor','pointer','scientific-y-axis-hit');
      yAxis.raise().on('dblclick.dkdsyaxis',toggleY);
      if(this.spec.xTitle!==false)svg.append('text').attr('class','dkds-scientific-axis-title').attr('x',margin.left+innerW/2).attr('y',height-10).attr('text-anchor','middle').text(this.spec.xTitle||'X');
      if(this.spec.yTitle!==false){const yTitle=svg.append('text').attr('class','dkds-scientific-axis-title dkds-scientific-y-axis-title').attr('transform',`translate(18,${margin.top+innerH/2}) rotate(-90)`).attr('text-anchor','middle').text(this.spec.yTitle||'Y').on('dblclick.dkdsyaxis',toggleY);selectionStyle(yTitle,'cursor','pointer','scientific-y-axis-title');}
      const configuredColorValues=this.spec.getColorDomainValues?.();const values=(Array.isArray(configuredColorValues)&&configuredColorValues.some(v=>this.finite(v))?configuredColorValues:curves.map(c=>c.colorValue)).filter(v=>this.finite(v)).map(Number);if(!values.length)values.push(0);const extent=d3.extent(values);if(extent[0]===extent[1]){extent[0]-=1;extent[1]+=1;}
      // Color-domain changes are semantic data changes, not selection/drag changes.
      // Keep the scale stable across geometry-only renders so external legends do
      // not rebuild or flicker when a marker is dragged or focus changes.
      const colorScaleKey=`${extent[0]}|${extent[1]}|${values.join(',')}`;let colorScale=this.colorScaleState?.key===colorScaleKey?this.colorScaleState.scale:null;
      if(!colorScale){colorScale=this.spec.colorScale?.({d3,extent,curves,values})||d3.scaleSequential(d3.interpolateTurbo).domain(extent);this.colorScaleState={key:colorScaleKey,scale:colorScale};this.spec.onColorScale?.(colorScale,{curves,extent,values});}
      const colorById=new Map(curves.map((curve,index)=>[String(curve.id),curve.color||(this.finite(curve.colorValue)?colorScale(Number(curve.colorValue)):this.categoricalColor(index))]));this.renderLegend({...legendMetrics,entries:this.legendEntries(allCurves)},allCurves);
      for(const curve of curves)this.ensureEntity(curve?.entityId||curve?.id);const selectedCurveIds=this.selectedCurveIds(),selectedCurveId=[...selectedCurveIds][0]||'',hasCurveSelection=selectedCurveIds.size>0,selectionVisuals=this.selectionVisuals(),dataLayer=svg.append('g').attr('clip-path',`url(#${clipId})`);
      const line=d3.line().defined(p=>this.finite(p.x)&&this.yDisplayable(p.y)).x(p=>x(p.x)).y(p=>y(this.yDisplayValue(p.y)));
      for(const curve of curves){
        const points=normalized.get(String(curve.id))||[],active=selectedCurveIds.has(String(curve.id)),color=colorById.get(String(curve.id))||this.categoricalColor(0),dash=curve.dash??(Number(curve.direction)<0?'7 4':null);
        const opacity=curve.opacity??(hasCurveSelection?(active?Number(selectionVisuals.curveActiveOpacity):Number(selectionVisuals.curveInactiveOpacity)):.74),strokeWidth=curve.strokeWidth??(hasCurveSelection?(active?Number(selectionVisuals.curveActiveWidth):Number(selectionVisuals.curveInactiveWidth)):1.25);
        dataLayer.append('path').datum(points).attr('class',`dkds-scientific-curve ${hasCurveSelection?(active?'is-focused':'is-dimmed'):''}`).attr('d',line).call(selectionPaint,'stroke',color).call(selectionPaint,'stroke-width',strokeWidth).call(selectionPaint,'stroke-dasharray',dash).call(selectionPaint,'opacity',opacity);
        dataLayer.append('path').datum(points).attr('class','dkds-scientific-curve-hit').attr('d',line)
          .on('click',(event)=>{event.stopPropagation();this.legendSelectedId=String(curve?.id||'');this.renderLegend({...legendMetrics,entries:this.legendEntries(allCurves)},allCurves);const [px]=d3.pointer(event,node),xValue=x.invert(px),index=this.nearestIndex(points,xValue),point=points[index],payload={curve,x:xValue,index:Number(point?.sourceIndex??index),point:point?.raw||point,event,surface:this,source:'curve-hit'};const decision=this.routeInteraction('click','curve',event,payload,{targetId:curve?.id});if(decision.handled)return;if(decision.intent==='select'){payload.additive=decision.binding?.selectionMode==='additive';if(this.spec.onCurveSelect)this.spec.onCurveSelect(payload);else if(this.spec.selectionTarget==='point')this.selectPoint(curve,point,index,{source:this.spec.source||'scientific-curve-point',additive:payload.additive});else this.selectEntity(curve?.entityId||curve?.id,{source:this.spec.source||'scientific-curve',additive:payload.additive,value:curve?.source||curve});}else if(decision.intent==='activate')this.spec.onCurveDoubleClick?.(payload);else if(decision.intent==='command'&&this.spec.onCurveModifiedClick)this.spec.onCurveModifiedClick(payload);})
          .on('dblclick',event=>{event.preventDefault();event.stopPropagation();const payload={curve,event,surface:this,source:'curve-hit'};const decision=this.routeInteraction('double-click','curve',event,payload,{targetId:curve?.id});if(decision.handled)return;if(decision.intent==='activate'){if(this.spec.onCurveDoubleClick)this.spec.onCurveDoubleClick(payload);else this.selectEntity(curve?.entityId||curve?.id,{source:this.spec.source||'scientific-curve-double',value:curve?.source||curve});}});
      }
      if(this.spec.selectionTarget==='point'&&this.selectionSnapshot?.items?.length){const selectedPoints=[],selectionKeys=this.selectedPointReferenceKeys();for(const curve of curves){const points=normalized.get(String(curve.id))||[];for(const point of points)if(this.pointSelected(curve,point,point.sourceIndex,selectionKeys))selectedPoints.push({curve,point,color:colorById.get(String(curve.id))||this.categoricalColor(0)});}dataLayer.append('g').attr('class','dkds-scientific-point-selection-layer').selectAll('circle.dkds-scientific-point-selection').data(selectedPoints).join('circle').attr('class','dkds-scientific-point-selection').attr('cx',row=>x(row.point.x)).attr('cy',row=>y(this.yDisplayValue(row.point.y))).attr('r',5).call(selectionPaint,'fill',row=>row.color).call(selectionPaint,'stroke','#fff').call(selectionPaint,'stroke-width',2);}
      const markers=this.markers();for(const marker of markers)this.ensureEntity(marker?.entityId||marker?.id,marker?.curveId||'');const selectedMarkerIds=this.selectedMarkerIds(),hasMarkerSelection=selectedMarkerIds.size>0,selectedMarker=markers.find(m=>selectedMarkerIds.has(String(m.id))),markerNodes=new Map(),curveById=new Map(curves.map(curve=>[String(curve.id),curve]));
      const manipulators=this.manipulators();
      const manipulatorByTarget=new Map(manipulators.filter(row=>row.kind==='point'&&row.targetId).map(row=>[String(row.targetId),row]));
      const emitManipulation=(phase,payload)=>{
        const fn=phase==='start'?this.spec.onManipulationStart:phase==='preview'?this.spec.onManipulationPreview:phase==='commit'?this.spec.onManipulationCommit:null;
        fn?.(payload);
      };
      const resetManipulator=(manipulator,event,handle='')=>{
        this.spec.onManipulationReset?.({manipulator,handle,event,surface:this});
        this.requestRender('manipulation-reset');
      };
      const snapToCurve=(manipulator,event)=>{
        const curveId=String(manipulator?.snap?.curveId||manipulator?.curveId||'');
        if(manipulator?.snap?.kind!=='curve'||!curveId)return {curve:null,index:-1,point:null,xValue:x.invert(event.x),yValue:y.invert(event.y)};
        const curve=curveById.get(curveId),points=normalized.get(curveId)||[];if(!curve||!points.length)return {curve:null,index:-1,point:null,xValue:x.invert(event.x),yValue:y.invert(event.y)};
        const idx=this.nearestIndex(points,x.invert(event.x)),point=points[idx],sourceIndex=Number.isFinite(Number(point?.sourceIndex))?Number(point.sourceIndex):idx;
        return {curve,index:sourceIndex,point:point?.raw||point,xValue:Number(point?.x),yValue:Number(point?.y)};
      };
      if(this.spec.showMarkers?.()!==false&&markers.length){
        const mobileVisualScale=document.documentElement?.classList?.contains('react-native-client') ? .78 : 1;
        const halos=dataLayer.append('g').attr('class','dkds-scientific-marker-selection-layer').selectAll('path.dkds-scientific-marker-selection-halo').data(markers.filter(marker=>selectedMarkerIds.has(String(marker?.id))),m=>m.id).join('path')
          .attr('class','dkds-scientific-marker-selection-halo').attr('d',m=>d3.symbol().type(this.symbolType(m.shape,d3)).size(360*mobileVisualScale)()).call(selectionPresentation,'display',m=>this.yDisplayable(m.y)?null:'none').attr('transform',m=>this.yDisplayable(m.y)?`translate(${x(Number(m.x))},${y(this.yDisplayValue(m.y))})`:null);
        const marks=dataLayer.append('g').selectAll('path.dkds-scientific-marker').data(markers,m=>m.id).join('path').attr('class',m=>`dkds-scientific-marker ${selectedMarkerIds.has(String(m.id))?'is-selected':''} ${m.locked?'is-locked':''} ${hasCurveSelection&&!selectedCurveIds.has(String(m.curveId))?'is-dimmed':''}`)
          .attr('d',m=>d3.symbol().type(this.symbolType(m.shape,d3)).size((selectedMarkerIds.has(String(m.id))?230:100)*mobileVisualScale)()).call(selectionPresentation,'display',m=>this.yDisplayable(m.y)?null:'none').attr('transform',m=>this.yDisplayable(m.y)?`translate(${x(Number(m.x))},${y(this.yDisplayValue(m.y))})`:null).call(selectionPaint,'fill',m=>m.color||'#2563eb')
          .call(selectionPaint,'stroke',m=>selectedMarkerIds.has(String(m.id))?'var(--dkui-marker-selected-stroke,#172033)':(m.accepted!==false?'#fff':'#6b7280')).call(selectionPaint,'stroke-width',m=>selectedMarkerIds.has(String(m.id))?3:1.8).call(selectionPaint,'opacity',m=>{const selected=selectedMarkerIds.has(String(m.id));let o=m.accepted!==false?Number(selectionVisuals.markerActiveOpacity):.34;if(hasMarkerSelection&&!selected)o=Math.min(o,Number(selectionVisuals.markerInactiveOpacity));if(hasCurveSelection&&!selectedCurveIds.has(String(m.curveId)))o=Math.min(o,Number(selectionVisuals.markerOtherCurveOpacity));return o;});
        const hits=dataLayer.append('g').selectAll('circle.dkds-scientific-marker-hit').data(markers,m=>m.id).join('circle').attr('class',m=>`dkds-scientific-marker-hit ${m.locked?'is-locked':''} ${manipulatorByTarget.has(String(m.id))?'is-manipulable':''}`).call(selectionPresentation,'display',m=>this.yDisplayable(m.y)?null:'none').attr('cx',m=>this.yDisplayable(m.y)?x(Number(m.x)):null).attr('cy',m=>this.yDisplayable(m.y)?y(this.yDisplayValue(m.y)):null).attr('r',m=>selectedMarkerIds.has(String(m.id))?12:10)
          .on('click',(event,marker)=>{event.stopPropagation();const id=String(marker?.id||'');if((this.markerClickSuppressUntil.get(id)||0)>Date.now()){event.preventDefault();return;}const payload={marker,event,surface:this,additive:false};const decision=this.routeInteraction('click','marker',event,payload,{targetId:id});if(decision.handled)return;if(decision.intent==='select'){payload.additive=decision.binding?.selectionMode==='additive';this.spec.onMarkerSelect?.(payload);}})
          .on('dblclick',(event,marker)=>{event.preventDefault();event.stopPropagation();const payload={marker,event,surface:this};const decision=this.routeInteraction('double-click','marker',event,payload,{targetId:marker?.id});if(decision.handled)return;if(decision.intent==='activate')this.spec.onMarkerDoubleClick?.(payload);})
          .on('contextmenu',(event,marker)=>{const payload={marker,event,surface:this};const decision=this.routeInteraction('context','marker',event,payload,{targetId:marker?.id,button:'secondary'});if(decision.handled){event.preventDefault();event.stopPropagation();return;}if(decision.intent==='context-menu'&&(event.ctrlKey||event.shiftKey)){event.preventDefault();event.stopPropagation();if(!marker.locked)this.spec.onMarkerDelete?.(payload);else this.spec.onLockedMarkerAction?.({marker,action:'delete',event,surface:this});}})
          .on('mouseenter',(event,marker)=>this.spec.onMarkerHover?.({marker,event,surface:this,phase:'enter'})).on('mousemove',(event,marker)=>this.spec.onMarkerHover?.({marker,event,surface:this,phase:'move'})).on('mouseleave',(event,marker)=>this.spec.onMarkerHover?.({marker,event,surface:this,phase:'leave'}));
        halos.each(function(marker){const id=String(marker?.id||'');if(!id)return;const row=markerNodes.get(id)||{};row.halo=this;markerNodes.set(id,row);});
        marks.each(function(marker){const id=String(marker?.id||'');if(!id)return;const row=markerNodes.get(id)||{};row.mark=this;markerNodes.set(id,row);});
        hits.each(function(marker){const id=String(marker?.id||'');if(!id)return;const row=markerNodes.get(id)||{};row.hit=this;markerNodes.set(id,row);});
        const dragState=new Map();
        hits.call(d3.drag().clickDistance(7).filter((event,marker)=>{const manipulator=manipulatorByTarget.get(String(marker?.id||''));return event.button===0&&!!manipulator&&this.canManipulate(manipulator,event);}).on('start',(event,marker)=>{
          const manipulator=manipulatorByTarget.get(String(marker.id));if(!manipulator||manipulator.locked||marker.locked)return;const geometry={x:Number(manipulator.geometry?.x??marker.x),y:Number(manipulator.geometry?.y??marker.y)};dragState.set(String(marker.id),{x:Number(event.x),y:Number(event.y),moved:false,manipulator,initialGeometry:{...geometry},geometry:{...geometry},curve:null,index:-1,point:null});emitManipulation('start',{manipulator,handle:'point',geometry:{...geometry},initialGeometry:{...geometry},event,surface:this});
        }).on('drag',(event,marker)=>{
          const state=dragState.get(String(marker.id));if(!state||state.manipulator.locked||marker.locked)return;if(!state.moved){state.moved=Math.hypot(Number(event.x)-state.x,Number(event.y)-state.y)>=5;if(!state.moved)return;}
          const snapped=snapToCurve(state.manipulator,event),axis=String(state.manipulator.axis||'xy');let nx=snapped.xValue,ny=snapped.yValue;if(axis==='x')ny=state.initialGeometry.y;if(axis==='y')nx=state.initialGeometry.x;state.geometry={x:Number(nx),y:Number(ny)};state.curve=snapped.curve;state.index=snapped.index;state.point=snapped.point;
          const payload={manipulator:state.manipulator,handle:'point',geometry:{...state.geometry},initialGeometry:{...state.initialGeometry},curve:snapped.curve,index:snapped.index,point:snapped.point,event,surface:this};emitManipulation('preview',payload);this.updateMarkerVisual(marker,{x:nx,y:ny});
        }).on('end',(event,marker)=>{
          const state=dragState.get(String(marker.id));dragState.delete(String(marker.id));if(!state?.moved)return;this.markerClickSuppressUntil.set(String(marker.id),Date.now()+160);emitManipulation('commit',{manipulator:state.manipulator,handle:'point',geometry:{...state.geometry},initialGeometry:{...state.initialGeometry},curve:state.curve,index:state.index,point:state.point,event,surface:this});this.requestRender('manipulation-end');
        }));
      }
      // Width/FWHM is presentation only here. Editing is owned by the generic
      // range manipulator below, so measurement semantics and interaction
      // semantics are no longer coupled.
      if(selectedMarker&&this.spec.showWidth?.()!==false){
        const widthSpec=this.spec.getMarkerWidth?.(selectedMarker)||selectedMarker.width;
        if(widthSpec){
          const finite=v=>this.finite(v),color=selectedMarker.color||'#2563eb';let measureLeft=finite(widthSpec.left)?Number(widthSpec.left):NaN,measureRight=finite(widthSpec.right)?Number(widthSpec.right):NaN;if(finite(measureLeft)&&finite(measureRight)&&measureLeft>measureRight)[measureLeft,measureRight]=[measureRight,measureLeft];
          const layer=svg.append('g').attr('clip-path',`url(#${clipId})`),baseline=widthSpec.baseline;
          if(baseline&&finite(baseline.x1)&&finite(baseline.x2)&&finite(baseline.y1)&&finite(baseline.y2))layer.append('line').attr('class','dkds-scientific-baseline-line').attr('x1',x(Number(baseline.x1))).attr('x2',x(Number(baseline.x2))).attr('y1',y(this.yDisplayValue(baseline.y1))).attr('y2',y(this.yDisplayValue(baseline.y2))).call(selectionPaint,'stroke',color);
          if(finite(measureLeft)&&finite(measureRight)&&measureRight>measureLeft){const yLeft=finite(widthSpec.yLeft)?Number(widthSpec.yLeft):(finite(widthSpec.y)?Number(widthSpec.y):Number(selectedMarker.y)),yRight=finite(widthSpec.yRight)?Number(widthSpec.yRight):yLeft,bandClass=`dkds-scientific-width-band${widthSpec.provisional?' is-provisional':''}`;layer.append('rect').attr('class',bandClass).attr('x',x(measureLeft)).attr('width',Math.max(2,x(measureRight)-x(measureLeft))).attr('y',margin.top).attr('height',innerH).call(selectionPaint,'fill',color);if(widthSpec.measureLine!==false){layer.append('line').attr('class','dkds-scientific-width-line').attr('x1',x(measureLeft)).attr('x2',x(measureRight)).attr('y1',y(this.yDisplayValue(yLeft))).attr('y2',y(this.yDisplayValue(yRight))).call(selectionPaint,'stroke',color);for(const row of [{x:measureLeft,y:yLeft},{x:measureRight,y:yRight}])layer.append('circle').attr('class','dkds-scientific-width-crossing').attr('cx',x(row.x)).attr('cy',y(this.yDisplayValue(row.y))).attr('r',3.5).call(selectionPaint,'fill','#fff').call(selectionPaint,'stroke',color).call(selectionPaint,'stroke-width',1.6);}}
        }
      }
      // Generic direct-manipulation primitives. These know only geometry,
      // snapping and constraints; domain meanings such as peak, threshold,
      // fit interval, crop window or FWHM belong entirely to the plugin.
      for(const manipulator of manipulators){
        if(!manipulator||manipulator.locked)continue;const kind=String(manipulator.kind),axis=String(manipulator.axis||'x'),g=manipulator.geometry||{},presentation=manipulator.presentation||{},color=presentation.color||'#2563eb';
        if(kind==='range'){
          let start=Number(g.start),end=Number(g.end);if(!Number.isFinite(start)||!Number.isFinite(end))continue;if(start>end)[start,end]=[end,start];
          const initialGeometry={start,end},constraints=manipulator.constraints||{},layer=svg.append('g').attr('class','dkds-direct-manipulation dkds-direct-range').attr('data-manipulator-id',String(manipulator.id)).attr('clip-path',`url(#${clipId})`),band=presentation.band===false?null:layer.append('rect').attr('class',`dkds-direct-range-band ${axis==='x'?'dkds-scientific-width-band':''}`).call(selectionPaint,'fill',color),handleNodes={};let moved=false,lastCurve=null,lastIndex=-1,lastPoint=null;
          const redraw=()=>{
            if(axis==='y'){
              const py0=y(this.yDisplayValue(start)),py1=y(this.yDisplayValue(end));band?.attr('x',margin.left).attr('width',innerW).attr('y',Math.min(py0,py1)).attr('height',Math.max(2,Math.abs(py1-py0)));
              for(const handle of ['start','end'])handleNodes[handle]?.attr('cx',String(presentation.handlePosition||'').toLowerCase()==='right'?margin.left+innerW-10:margin.left+10).attr('cy',y(this.yDisplayValue(handle==='start'?start:end)));
            }else{
              const px0=x(start),px1=x(end);band?.attr('x',Math.min(px0,px1)).attr('width',Math.max(2,Math.abs(px1-px0))).attr('y',margin.top).attr('height',innerH);
              const handleY=String(presentation.handlePosition||'').toLowerCase()==='bottom'?margin.top+innerH-10:(Number.isFinite(Number(presentation.handlePosition))?y(this.yDisplayValue(Number(presentation.handlePosition))):margin.top+10);
              for(const handle of ['start','end'])handleNodes[handle]?.attr('cx',x(handle==='start'?start:end)).attr('cy',handleY);
            }
          };
          const installRangeDrag=(handleNode,handle)=>handleNode.on('click',event=>event.stopPropagation()).on('dblclick',event=>{event.preventDefault();event.stopPropagation();resetManipulator(manipulator,event,handle);}).call(d3.drag().clickDistance(5).filter(event=>event.button===0&&this.canManipulate(manipulator,event)).on('start',event=>{moved=false;lastCurve=null;lastIndex=-1;lastPoint=null;emitManipulation('start',{manipulator,handle,geometry:{start,end},initialGeometry:{...initialGeometry},event,surface:this});}).on('drag',event=>{
            let value,curve=null,index=-1,point=null;if(axis==='x'){const snapped=snapToCurve(manipulator,event);value=Number(snapped.xValue);curve=snapped.curve;index=snapped.index;point=snapped.point;}else{value=Number(y.invert(event.y));if(this.displayYAxisType==='log'){const seed=handle==='start'?initialGeometry.start:initialGeometry.end;value=(Number(seed)<0?-1:1)*value;}}if(!Number.isFinite(value))return;
            const min=Number(constraints.min),max=Number(constraints.max),minSpan=Math.max(0,Number(constraints.minSpan)||0),contains=Number(constraints.contains),containsGap=Math.max(0,Number(constraints.containsGap)||0);if(Number.isFinite(min))value=Math.max(min,value);if(Number.isFinite(max))value=Math.min(max,value);
            if(handle==='start'){value=Math.min(value,end-minSpan);if(Number.isFinite(contains))value=Math.min(value,contains-containsGap);start=value;}else{value=Math.max(value,start+minSpan);if(Number.isFinite(contains))value=Math.max(value,contains+containsGap);end=value;}
            if(!(Number.isFinite(start)&&Number.isFinite(end)&&end>=start))return;moved=true;lastCurve=curve;lastIndex=index;lastPoint=point;redraw();emitManipulation('preview',{manipulator,handle,geometry:{start,end},initialGeometry:{...initialGeometry},curve,index,point,event,surface:this});
          }).on('end',event=>{if(!moved)return;emitManipulation('commit',{manipulator,handle,geometry:{start,end},initialGeometry:{...initialGeometry},curve:lastCurve,index:lastIndex,point:lastPoint,event,surface:this});this.requestRender('manipulation-end');}));
          for(const handle of ['start','end']){const h=layer.append('circle').attr('class',`dkds-direct-handle dkds-direct-range-handle ${axis==='x'?'dkds-scientific-width-handle':''}`).attr('data-handle',handle).attr('r',6).call(selectionPaint,'fill','#fff').call(selectionPaint,'stroke',color).call(selectionPaint,'stroke-width',2);handleNodes[handle]=h;installRangeDrag(h,handle);}redraw();
        }else if(kind==='axis'){
          let value=Number(g.value);if(!Number.isFinite(value))continue;const initialGeometry={value},layer=svg.append('g').attr('class','dkds-direct-manipulation dkds-direct-axis').attr('data-manipulator-id',String(manipulator.id)).attr('clip-path',`url(#${clipId})`),lineNode=layer.append('line').attr('class','dkds-direct-axis-line').call(selectionPaint,'stroke',color),handleNode=layer.append('circle').attr('class',`dkds-direct-handle dkds-direct-axis-handle is-${axis}-axis`).attr('r',6).call(selectionPaint,'fill','#fff').call(selectionPaint,'stroke',color).call(selectionPaint,'stroke-width',2);const redraw=()=>{if(axis==='y'){lineNode.attr('x1',margin.left).attr('x2',margin.left+innerW).attr('y1',y(this.yDisplayValue(value))).attr('y2',y(this.yDisplayValue(value)));handleNode.attr('cx',margin.left+10).attr('cy',y(this.yDisplayValue(value)));}else{lineNode.attr('x1',x(value)).attr('x2',x(value)).attr('y1',margin.top).attr('y2',margin.top+innerH);handleNode.attr('cx',x(value)).attr('cy',margin.top+10);}};let moved=false;handleNode.on('click',event=>event.stopPropagation()).on('dblclick',event=>{event.preventDefault();event.stopPropagation();resetManipulator(manipulator,event,'value');}).call(d3.drag().clickDistance(5).filter(event=>event.button===0&&this.canManipulate(manipulator,event)).on('start',event=>{moved=false;emitManipulation('start',{manipulator,handle:'value',geometry:{value},initialGeometry:{...initialGeometry},event,surface:this});}).on('drag',event=>{let curve=null,index=-1,point=null,next;if(axis==='x'){const snapped=snapToCurve(manipulator,event);next=Number(snapped.xValue);curve=snapped.curve;index=snapped.index;point=snapped.point;}else{next=Number(y.invert(event.y));if(this.displayYAxisType==='log')next=(Number(initialGeometry.value)<0?-1:1)*next;}if(!Number.isFinite(next))return;moved=true;const min=Number(manipulator.constraints?.min),max=Number(manipulator.constraints?.max);if(Number.isFinite(min))next=Math.max(min,next);if(Number.isFinite(max))next=Math.min(max,next);value=next;redraw();emitManipulation('preview',{manipulator,handle:'value',geometry:{value},initialGeometry:{...initialGeometry},curve,index,point,event,surface:this});}).on('end',event=>{if(!moved)return;emitManipulation('commit',{manipulator,handle:'value',geometry:{value},initialGeometry:{...initialGeometry},event,surface:this});this.requestRender('manipulation-end');}));redraw();
        }else if(kind==='point'&&!manipulator.targetId){
          let px=Number(g.x),py=Number(g.y);if(!Number.isFinite(px)||!Number.isFinite(py))continue;const initialGeometry={x:px,y:py},layer=svg.append('g').attr('class','dkds-direct-manipulation dkds-direct-point').attr('data-manipulator-id',String(manipulator.id)).attr('clip-path',`url(#${clipId})`),handleNode=layer.append('circle').attr('class','dkds-direct-handle dkds-direct-point-handle').attr('r',6).call(selectionPaint,'fill','#fff').call(selectionPaint,'stroke',color).call(selectionPaint,'stroke-width',2).attr('cx',x(px)).attr('cy',y(this.yDisplayValue(py)));let moved=false;handleNode.on('dblclick',event=>{event.preventDefault();event.stopPropagation();resetManipulator(manipulator,event,'point');}).call(d3.drag().clickDistance(5).filter(event=>event.button===0&&this.canManipulate(manipulator,event)).on('start',event=>{moved=false;emitManipulation('start',{manipulator,handle:'point',geometry:{x:px,y:py},initialGeometry:{...initialGeometry},event,surface:this});}).on('drag',event=>{const snapped=snapToCurve(manipulator,event),dragAxis=String(manipulator.axis||'xy');let nx=Number(snapped.xValue),ny=Number(snapped.yValue);if(dragAxis==='x')ny=initialGeometry.y;if(dragAxis==='y')nx=initialGeometry.x;if(!Number.isFinite(nx)||!Number.isFinite(ny))return;moved=true;px=nx;py=ny;handleNode.attr('cx',x(px)).attr('cy',y(this.yDisplayValue(py)));emitManipulation('preview',{manipulator,handle:'point',geometry:{x:px,y:py},initialGeometry:{...initialGeometry},curve:snapped.curve,index:snapped.index,point:snapped.point,event,surface:this});}).on('end',event=>{if(!moved)return;emitManipulation('commit',{manipulator,handle:'point',geometry:{x:px,y:py},initialGeometry:{...initialGeometry},event,surface:this});this.requestRender('manipulation-end');}));
        }
      }
      this.spec.afterRender?.({svg,dataLayer,x,y,curves,markers,width,height,margin,innerW,innerH,clipId,colorScale,surface:this});
      let rangeDrag=null;plotBg.on('pointerdown',event=>{if(event.button!==0)return;const touchLike=event.pointerType==='touch'||event.pointerType==='pen';if(touchLike&&String(this.spec.mobileBoxGesture||'none')==='none')return;this.spec.onRangeStart?.({event,surface:this});const [px,py]=d3.pointer(event,node),sx=Math.max(margin.left,Math.min(margin.left+innerW,px)),sy=Math.max(margin.top,Math.min(margin.top+innerH,py));rangeDrag={pointerId:event.pointerId,sx,sy,ex:sx,ey:sy,moved:false,mobileIntent:touchLike?String(this.spec.mobileBoxGesture||'none'):''};try{plotBg.node().setPointerCapture(event.pointerId);}catch{}event.preventDefault();}).on('pointermove',event=>{if(!rangeDrag||rangeDrag.pointerId!==event.pointerId)return;const [px,py]=d3.pointer(event,node);rangeDrag.ex=Math.max(margin.left,Math.min(margin.left+innerW,px));rangeDrag.ey=Math.max(margin.top,Math.min(margin.top+innerH,py));rangeDrag.moved=rangeDrag.moved||Math.hypot(rangeDrag.ex-rangeDrag.sx,rangeDrag.ey-rangeDrag.sy)>=5;if(!rangeDrag.moved)return;const preview=this.behavior?.resolve?.({gesture:'box',target:'background',event,payload:{surface:this}}),zoom=rangeDrag.mobileIntent==='zoom-box'||preview?.intent==='zoom-box';svg.selectAll('.dkds-scientific-direct-box').remove();svg.append('rect').attr('class',`dkds-scientific-direct-box ${zoom?'is-zoom':'is-range'}`).attr('x',Math.min(rangeDrag.sx,rangeDrag.ex)).attr('y',Math.min(rangeDrag.sy,rangeDrag.ey)).attr('width',Math.abs(rangeDrag.ex-rangeDrag.sx)).attr('height',Math.abs(rangeDrag.ey-rangeDrag.sy));event.preventDefault();});
      const finishRange=event=>{if(!rangeDrag||rangeDrag.pointerId!==event.pointerId)return;const drag=rangeDrag;rangeDrag=null;svg.selectAll('.dkds-scientific-direct-box').remove();try{plotBg.node().releasePointerCapture(event.pointerId);}catch{}
        if(!drag.moved){const near=this.nearestCurveAtPixel(drag.sx,drag.sy,x,y,curves,Number(this.spec.nearestDistance)||18);if(near){this.legendSelectedId=String(near.curve?.id||'');this.renderLegend({...legendMetrics,entries:this.legendEntries(allCurves)},allCurves);const payload={curve:near.curve,x:near.point.x,index:near.index,point:near.point?.raw||near.point,event,surface:this,source:'background'};const decision=this.routeInteraction('click','curve',event,payload,{targetId:near.curve?.id});if(decision.handled)return;if(decision.intent==='select'){payload.additive=decision.binding?.selectionMode==='additive';if(this.spec.onCurveSelect)this.spec.onCurveSelect(payload);else if(this.spec.selectionTarget==='point')this.selectPoint(near.curve,near.point,near.index,{source:this.spec.source||'scientific-curve-background-point',additive:payload.additive});else this.selectEntity(near.curve?.entityId||near.curve?.id,{source:this.spec.source||'scientific-curve-background',additive:payload.additive,value:near.curve?.source||near.curve});}else if(decision.intent==='command'&&this.spec.onCurveModifiedClick)this.spec.onCurveModifiedClick(payload);}else{const payload={event,surface:this,source:'background'};const decision=this.routeInteraction('click','background',event,payload);if(decision.handled)return;if(decision.intent==='clear-selection'){this.legendSelectedId='';this.renderLegend({...legendMetrics,entries:this.legendEntries(allCurves)},allCurves);if(this.spec.onClearSelection)this.spec.onClearSelection(payload);else this.interaction?.clear?.({source:this.spec.source||'scientific-curve-background'});}}return;}
        const sx0=Math.min(drag.sx,drag.ex),sx1=Math.max(drag.sx,drag.ex),sy0=Math.min(drag.sy,drag.ey),sy1=Math.max(drag.sy,drag.ey);if(Math.abs(sx1-sx0)<6||Math.abs(sy1-sy0)<6)return;const selection={xMin:Math.min(x.invert(sx0),x.invert(sx1)),xMax:Math.max(x.invert(sx0),x.invert(sx1)),yMin:Math.min(y.invert(sy0),y.invert(sy1)),yMax:Math.max(y.invert(sy0),y.invert(sy1)),curveId:selectedCurveId,event,surface:this,target:String(this.spec.rangeSelectionTarget||'samples'),targetType:String(this.spec.rangeSelectionType||'')};selection.markers=markers.filter(marker=>{const my=this.yDisplayValue(marker?.y);return this.finite(marker?.x)&&Number.isFinite(my)&&Number(marker.x)>=selection.xMin&&Number(marker.x)<=selection.xMax&&my>=selection.yMin&&my<=selection.yMax;});selection.markerIds=selection.markers.map(marker=>String(marker?.entityId||marker?.id||'')).filter(Boolean);const decision=this.routeInteraction('box','background',event,selection),resolvedIntent=drag.mobileIntent&&drag.mobileIntent!=='none'?drag.mobileIntent:decision.intent;if(decision.handled)return;if(resolvedIntent==='zoom-box'){const next={xDomain:[selection.xMin,selection.xMax],yDomain:[selection.yMin,selection.yMax]};this.setView(next,{reason:'box-zoom',event});this.requestRender('box-zoom');return;}if(resolvedIntent==='select-region')this.spec.onRangeSelect?.(selection);
      };plotBg.on('pointerup',finishRange).on('pointercancel',()=>{rangeDrag=null;svg.selectAll('.dkds-scientific-direct-box').remove();});
      plotBg.on('dblclick',event=>{event.preventDefault();const decision=this.routeInteraction('double-click','background',event,{event,surface:this});if(decision.handled)return;if(decision.intent==='reset-view')this.resetView({event});});
      svg.on('wheel.dkdssci',event=>{const [px,py]=d3.pointer(event,node);if(px<margin.left||px>margin.left+innerW||py<margin.top||py>margin.top+innerH)return;const payload={event,surface:this,x:x.invert(px),y:y.invert(py)};const decision=this.routeInteraction('wheel','plot',event,payload);if(decision.handled)return;if(decision.intent!=='zoom-wheel')return;event.preventDefault();event.stopPropagation();this.spec.onWheelZoomStart?.({event,surface:this});const dy=Math.max(-220,Math.min(220,Number(event.deltaY)||0)),factor=Math.max(.72,Math.min(1.38,Math.exp(dy*.00145))),cx=x.invert(px),cy=y.invert(py),minX=Math.max(1e-12,Math.abs(fullX[1]-fullX[0])*1e-6),minY=logY?1e-6:Math.max(1e-30,Math.abs(fullY[1]-fullY[0])*1e-6),next={xDomain:this.scaleDomainAround(xDomain,cx,factor,minX),yDomain:this.scaleDomainAround(yDomain,cy,factor,minY,logY?'log':'linear')};this.setView(next,{reason:'wheel',event});this.requestRender('wheel');});
      const selectedRange=this.spec.getRangeSelection?.();if(selectedRange&&this.finite(selectedRange.xMin??selectedRange.min)&&this.finite(selectedRange.xMax??selectedRange.max)){
        const xv0=Number(selectedRange.xMin??selectedRange.min),xv1=Number(selectedRange.xMax??selectedRange.max),rx0=x(xv0),rx1=x(xv1),hasY=this.finite(selectedRange.yMin)&&this.finite(selectedRange.yMax),yv0=hasY?Number(selectedRange.yMin):null,yv1=hasY?Number(selectedRange.yMax):null,ry0=hasY?y(this.yDisplayValue(yv0)):margin.top+innerH,ry1=hasY?y(this.yDisplayValue(yv1)):margin.top;
        if(Number.isFinite(rx0)&&Number.isFinite(rx1)&&Number.isFinite(ry0)&&Number.isFinite(ry1)){
          const xLo=Math.min(xv0,xv1),xHi=Math.max(xv0,xv1),yLo=hasY?Math.min(yv0,yv1):-Infinity,yHi=hasY?Math.max(yv0,yv1):Infinity;
          svg.append('rect').attr('class','dkds-scientific-persisted-range').attr('x',Math.min(rx0,rx1)).attr('y',Math.min(ry0,ry1)).attr('width',Math.abs(rx1-rx0)).attr('height',Math.abs(ry1-ry0));
          const rangeTarget=String(this.spec.rangeSelectionTarget||'samples');
          if(rangeTarget==='markers'){
            const rangeMarkers=markers.filter(marker=>this.finite(marker?.x)&&this.finite(marker?.y)&&Number(marker.x)>=xLo&&Number(marker.x)<=xHi&&Number(marker.y)>=yLo&&Number(marker.y)<=yHi);
            const selectedLayer=dataLayer.append('g').attr('class','dkds-scientific-range-markers');
            selectedLayer.selectAll('circle').data(rangeMarkers,marker=>String(marker?.id||marker?.entityId||'')).join('circle').attr('cx',marker=>x(Number(marker.x))).attr('cy',marker=>y(this.yDisplayValue(marker.y))).attr('r',8.5).call(selectionPaint,'fill','rgba(255,255,255,.18)').call(selectionPaint,'stroke',marker=>marker?.color||'#315efb').call(selectionPaint,'stroke-width',2.2);
          }else{
            const selectedLayer=dataLayer.append('g').attr('class','dkds-scientific-range-points');
            for(const curve of curves){const points=(normalized.get(String(curve.id))||[]).filter(point=>{const py=this.yDisplayValue(point.y);return point.x>=xLo&&point.x<=xHi&&py>=yLo&&py<=yHi;});if(!points.length)continue;const color=curve.color||colorScale(this.finite(curve.colorValue)?Number(curve.colorValue):0),path=points.map(point=>`M${x(point.x).toFixed(2)},${y(this.yDisplayValue(point.y)).toFixed(2)}h0`).join('');selectedLayer.append('path').attr('d',path).call(selectionPaint,'fill','none').call(selectionPaint,'stroke',color).call(selectionPaint,'stroke-width',4.2).call(selectionPaint,'stroke-linecap','round').call(selectionPaint,'opacity',.96);}
          }
        }
      }
      this.lastRender={reason,width,height,x,y,colorScale,curves,markers,margin,innerW,innerH,clipId,dataLayer,markerNodes,yScaleType:this.displayYAxisType};requestAnimationFrame(()=>{this.clampNavigationTools();this.scheduleNavigationCollisionCheck();});return true;
    }
    dispose(){if(this.disposed)return;this.disposed=true;this.selectionOff?.();this.selectionOff=null;this.resizeObserver?.disconnect?.();this.navObstacleObserver?.disconnect?.();this.navObstacleObserver=null;clearTimeout(this.navTouchHideTimer);this.navTouchHideTimer=null;if(this.navTouchRevealHandler&&this.container)try{this.container.removeEventListener('pointerdown',this.navTouchRevealHandler,true);}catch{}this.navTouchRevealHandler=null;if(this.navCollisionFrame){cancelAnimationFrame(this.navCollisionFrame);this.navCollisionFrame=0;}try{this.d3()?.select(this.target)?.on('.dkdssci',null);}catch{}this.target.classList.remove('dkds-scientific-curve-surface');if(this.target.getAttribute?.('data-dkds-touch-gesture-owner')==='scientific-plot'){if(this.previousTouchGestureOwner===null||this.previousTouchGestureOwner===undefined)this.target.removeAttribute?.('data-dkds-touch-gesture-owner');else this.target.setAttribute?.('data-dkds-touch-gesture-owner',this.previousTouchGestureOwner);}delete this.target.dataset.dkdsMobileBoxGesture;if(this.ownsTarget)this.target.remove?.();try{this.navTouchDragCleanup?.();}catch{}this.navTouchDragCleanup=null;this.navTools?.remove?.();this.navTools=null;this.legendController?.dispose?.();this.legendController=null;this.legendHost=null;this.legendGroupOff?.();this.legendGroupOff=null;this.legendGroup=null;if(this.layoutFallbackOwned){this.container?.classList?.remove('dkds-scientific-layout-fallback');this.container?.style?.removeProperty?.('--dkds-scientific-preferred-min-height');this.layoutFallbackOwned=false;}this.container?.removeAttribute?.('data-dkds-scientific-layout');this.container?.classList?.remove('dkds-scientific-surface-host');}
  }
  for(const name of Object.getOwnPropertyNames(ScientificCurveRenderMixin.prototype)){
    if(name==='constructor')continue;
    Object.defineProperty(ScientificCurveSurface.prototype,name,Object.getOwnPropertyDescriptor(ScientificCurveRenderMixin.prototype,name));
  }
  return ScientificCurveSurface;
}
module.exports=Object.freeze({applyScientificCurveRender});
